### ISSUE TITLE
pod库中文件与demo中文件不一致

### ISSUE THREAD

**Issue by xtcqw** [Tencent/Hippy#105]
**Describe the bug**
SDK: 2.0.0
pod->UIView+React
demo->UIView+Hippy

**Expected behavior**
更新pod库，与demo中保持一致

**Screenshots**
![52508EE15EC385F1BD7C57B36187A933](https://user-images.githubusercontent.com/21976533/72032861-9fdc8280-32cb-11ea-9c37-32e01c65bc91.jpg)

**Comment by ozonelmy** [comment]
pod引用的是tag 2.0.0版本。UIView+React.h改名为UIView+Hippy.h是在2.0.0之后改的。

**Comment by xtcqw** [comment]
我知道啊，我是说可以打个新tag，更新一下pod
