### ISSUE TITLE
Modal组件不生效

### ISSUE THREAD

**Issue by xuezhimin** [Tencent/Hippy#1057]
**modal组件不生效**
我自己在网上找了相关例子和hippy Api ,实现了下面的例子，

//-----------------布局代码
<Modal animationType="fade" transparent={false} visible={this.state.gBookModalVisible} presentationStyle="formSheet"
                       onRequestClose={() => {this.setState({gBookModalVisible: false})}}>
                    <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', alignItems: 'center', justifyContent: 'center'}}>
                        <Text>我是GBook弹框</Text>
                    </View>
</Modal>

//---------------触发函数 弹框弹起
 gBookModalSwitch(){
        this.setState({
            gBookModalVisible: !this.state.gBookModalVisible,
        })
    }

上述是代码实现，烦请大佬们指点指点

**Comment by zoomchan-cxj** [comment]
先按照examples里的demo使用看看

**Comment by xuezhimin** [comment]
> github examples里有具体的Modal demo，先简化你的代码自行测试下

好的
