### ISSUE TITLE
li标签的吸顶事件在ios和安卓的触发时机不一致

### ISSUE THREAD

**Issue by Volcano-Yang** [Tencent/Hippy#1118]
**Describe the bug**
li标签的吸顶事件在ios和安卓的触发时机不一致。同一个设置了sticky属性为true的li标签，ios是当这个li的上顶边被遮盖，就开始吸顶 。安卓是下底边被遮盖，才会开始吸顶。 

![image](https://user-images.githubusercontent.com/43328103/143438146-2d4b8af7-0b09-4a9b-b957-3ad6a73db452.png)

**To Reproduce**
这是一个已知问题，li-demo在在手Q中就可以复现。

**Expected behavior**
希望能够统一成上顶边被遮盖就开始吸顶，这才符合吸顶的概念。

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPhone10 xR and huawei p20
- Front-end SDK and version： "@hippy/vue": "^2.3.3",  "@hippy/vue-native-components": "^2.0.3",

**Comment by zoomchan-cxj** [comment]
hippy3.0 统一解决
