### ISSUE TITLE
[Bug Report] Get empty page and warning when opening ul/li case in web mode

### ISSUE THREAD

**Issue by boxizen** [Tencent/Hippy#116]
**Describe the bug**
Get empty page and warning when opening ul/li case in web mode(hippy-vue-demo).

**To Reproduce**
1. Go to the root directory of 'examples/hippy-vue-demo'
2. Run command 'npm run serve'
3. open 'http://localhost:8080/#/' in browser and click 'ul/li 组件'

**Expected behavior**
Show the demo list and no warning in console.

**Screenshots**
![企业微信截图_8f0dab5f-553b-4ed4-84f1-85b09557eaa7](https://user-images.githubusercontent.com/6027456/72202088-6b68f200-3496-11ea-8954-5002f7b66b8f.png)

**Comment by xuqingkuang** [comment]
I will take a look at it later.

The code was working before.
