### ISSUE TITLE
想知道原理是什么，能告知一下吗？

### ISSUE THREAD

**Issue by YellowDoing** [Tencent/Hippy#119]
官方文档和README.md对原理只字不提，是要隐瞒什么？原理无非就那么2个，原生渲染类似rn，webview渲染类似codova，或者混合渲染类似uniapp，讲一下原理不行？

**Comment by YellowDoing** [comment]
类似flutter那种引擎渲染是不可能的，腾讯没有那个技术能力和底蕴

**Comment by chihong2012** [comment]
类似RN呀。说简单点，前端的控件，会对应成原生的控件。

**Comment by xuqingkuang** [comment]
原理在之前好几次大会上都有提过了，前端的 [VueConf 2019 杭州](https://www.bilibili.com/video/av37464898)，终端层的 [GTMC 2018 北京](https://gmtc.infoq.cn/2019/beijing/presentation/1847)、[GMTC 2019 深圳](https://gmtc.infoq.cn/2019/shenzhen/presentation/2234)。

自己去找 PPT 吧。

**Comment by yFeii** [comment]
![image](https://user-images.githubusercontent.com/24515770/97822770-e1726a00-1cf1-11eb-9b37-3ecd873de89a.png)
你好 可以发下这个 ppt么，我看infoq上面没有ppt链接
