### ISSUE TITLE
Android Demo 中 ul/li 加载更多图片时闪烁

### ISSUE THREAD

**Issue by XiangliJiaxing** [Tencent/Hippy#120]
**Describe the bug**
当加载更多时，图片会整体闪烁；

**Comment by XiangliJiaxing** [comment]
查看源码，发现对应的原生控件com.tencent.mtt.hippy.views.image/HippyImageView 没有相关的缓存处理逻辑；

**Comment by xuqingkuang** [comment]
已经修复。
