### ISSUE TITLE
想请教一下关于 JSI/Core C++/Bindings 这几个概念在 Hippy 中是否指的是同一类技术手段？和 RN 的 JSI 是一样的吗？如果相比于使用 JSON 传输性能有很大提升为何没有所有地方都使用？

### ISSUE THREAD

**Issue by OneeMe** [Tencent/Hippy#1203]
## 问题起因

在 Hippy 的 InfoQ 分享 PPT 中提及到 Binding，然后在官方文档中看到  JSI/Core C++ 这两个名词

## 核心问题

1. JSI/Core C++/Bindings  这几个名词在 Hippy 的语境下是否是相同的？如果不是，他们分别指代什么？如果是，是否统一一下称呼比较好？
2. 在 Hippy 文档的 JSI 介绍中提及到了其不适用于所有场景，可以看到目前最影响性能的 UIManager 相关的 Native Module 都没有使用这种模式，是因为 UIManger 的数据量也很大导致使用 JSI 这种模式也没有很好的性能提升么？

**Comment by churchill-zhang** [comment]
1. JSI/Core C++/Bindings 在 Hippy 下是不同的概念
a. JSI 是可直接和android、iOS客户端通讯的一套机制，具有低延迟的特性
b. Core C++ 代表 Hippy 对android、iOS共有代码的抽象
c. Bindings代表 Hippy 提供的 C++ 方法和前端 function的绑定机制

2. JSI 对于数据量很大，但是取其中一个key，类似灰度开关数据很多，需要取其中一个key的场景非常使用，延迟非常低，速度很快。但对于大量数据通讯，特别需要迭代获取的场景并不占优势（例如如果对象 { a:1, b:2, c:3, ..., z:26, z1: 27, ..., z10000: 100027} 超大数据对象取a这个key对应的value(1)的时候非常快，但是如果业务要使用所有的key(a到z10000)，jsi的性能并不如传统的编解码。jsi需要遍历迭代的通过每一个key取每一个值，编解码可以一次性将native的对象直接转成js对象，然后从js引擎中取值。

**Comment by OneeMe** [comment]
@churchill-zhang 明白了，不过这几种名词，底层的 JS 和 Native 数据交换的实现，应该都是通过 JSC （在 iOS上）提供的 C 那一层的 API 完成的吧？如果是的话，那么两个语言间的 “对象转换” 在大数据量的场景下就成了瓶颈。
我在想，桥通信的主要瓶颈目前看起来就卡在这个 “对象转换” 上，有没有可能用直接用传地址的方式直接让两边通信？

**Comment by churchill-zhang** [comment]
传地址不行，iOS上oc无法直接通过地址访问js对象，因为无法直接获取js对象的生命周期。有可能访问的时候，js已经标记回收了。oc可以间接通过jsc的接口操作js对象，但是jsc为了安全，接口内部都加了锁，所以频繁调用接口的效率并不如直接通过jsc的整体转换接口换成js对象，js引擎内部操作对象并不需要加锁（单线程）。

**Comment by OneeMe** [comment]
理解。
锁带来的性能损耗确实无法规避，不过 js 对象的生命周期通过 JSManagedValue 是不是能够（部分）解决？
