### ISSUE TITLE
建议完善英文版文档

### ISSUE THREAD

**Issue by hugetiny** [Tencent/Hippy#129]
如题

**Comment by hugetiny** [comment]
Hippy很好的给出一个解决方案。
为了和其他框架整合，我目前正在用Quasar做一个项目，手机端支持框架只有Cordova和Capacitor，不太给力。希望完善英文版文档，以便和其他框架提PR

**Comment by xuqingkuang** [comment]
建议采纳，在计划进行中，但全文翻译还需要些时间，谢谢！
