### ISSUE TITLE
官方文档呢哥  文档呢?

### ISSUE THREAD

**Issue by wangjun521** [Tencent/Hippy#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xuqingkuang** [comment]
文档目前还比较散，会整理一下稍后推出。

可以先从首页的 [开始](https://github.com/Tencent/Hippy/blob/master/README.zh_CN.md#开始) 章节把范例工程先运行起来。

范例工程已经是最佳实践，包含了所有组件的使用方法了。

如果使用 VS Code 作为编辑器会使用代码中的注释作为说明。

**Comment by xuqingkuang** [comment]
先打开，作为 TODO

**Comment by huangshengjie** [comment]
笑哭，半吊子的东西就不要拿出来秀了

**Comment by imhazige** [comment]
看起来很好，结果打开，文档就这样。估计是没钱……

**Comment by fubd** [comment]
有点好奇 tencent大概投入了多少人开发hippy @xuqingkuang

**Comment by cbqin** [comment]
感觉现在开源个项目就像炒小鲜肉一样的。

**Comment by xuqingkuang** [comment]
> 有点好奇 tencent大概投入了多少人开发hippy @xuqingkuang

陆陆续续参加项目的可以参考一下  AUTHORS  文件。

**Comment by xuqingkuang** [comment]
Duplicated with #21, close it first, the documentation update progress will update in the issue #21
