### ISSUE TITLE
hippy-react运行报错

### ISSUE THREAD

**Issue by pengzhengang** [Tencent/Hippy#130]
Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from E:\Mayun\Hippy\hippy-react\hippy-react-demo
× ｢wdm｣: ModuleNotFoundError: Module not found: Error: Can't resolve '@hippy/react' in 'E:\Mayun\Hippy\hippy-react\hippy-react-demo\src'
    at factory.create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\Compilation.js:925:10)
    at factory (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:401:22)
    at resolver (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
    at asyncLib.parallel (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
    at E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\neo-async\async.js:2830:7
    at E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\neo-async\async.js:6877:13
    at normalResolver.resolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
    at doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:213:14)
    at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7)
    at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
    at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43)
× ｢wdm｣: resolve '@hippy/react' in 'E:\Mayun\Hippy\hippy-react\hippy-react-demo\src'
  Parsed request is a module
  using description file: E:\Mayun\Hippy\hippy-react\hippy-react-demo\package.json (relative path: ./src)
    aliased with mapping '@hippy/react': 'E:\Mayun\Hippy\packages\hippy-react-web' to 'E:\Mayun\Hippy\packages\hippy-react-web'
      using description file: E:\Mayun\Hippy\hippy-react\hippy-react-demo\package.json (relative path: ./src)
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          E:\Mayun\Hippy\packages\hippy-react-web doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          E:\Mayun\Hippy\packages\hippy-react-web.js doesn't exist
        .jsx
          Field 'browser' doesn't contain a valid alias configuration
          E:\Mayun\Hippy\packages\hippy-react-web.jsx doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          E:\Mayun\Hippy\packages\hippy-react-web.json doesn't exist
        as directory
          E:\Mayun\Hippy\packages\hippy-react-web doesn't exist
i ｢wdm｣: wait until bundle finished: /

**Comment by jeromehan** [comment]
> @hippy/react

npm i @hippy/react

**Comment by jeromehan** [comment]
> Project is running at http://localhost:8080/
> i ｢wds｣: webpack output is served from /
> i ｢wds｣: Content not from webpack is served from E:\Mayun\Hippy\hippy-react\hippy-react-demo
> × ｢wdm｣: ModuleNotFoundError: Module not found: Error: Can't resolve '@hippy/react' in 'E:\Mayun\Hippy\hippy-react\hippy-react-demo\src'
> at factory.create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\Compilation.js:925:10)
> at factory (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:401:22)
> at resolver (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
> at asyncLib.parallel (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
> at E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\neo-async\async.js:2830:7
> at E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\neo-async\async.js:6877:13
> at normalResolver.resolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
> at doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:213:14)
> at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
> at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), :15:1)
> at resolver.doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7)
> at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
> at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), :15:1)
> at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
> at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), :27:1)
> at resolver.doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43)
> × ｢wdm｣: resolve '@hippy/react' in 'E:\Mayun\Hippy\hippy-react\hippy-react-demo\src'
> Parsed request is a module
> using description file: E:\Mayun\Hippy\hippy-react\hippy-react-demo\package.json (relative path: ./src)
> aliased with mapping '@hippy/react': 'E:\Mayun\Hippy\packages\hippy-react-web' to 'E:\Mayun\Hippy\packages\hippy-react-web'
> using description file: E:\Mayun\Hippy\hippy-react\hippy-react-demo\package.json (relative path: ./src)
> Field 'browser' doesn't contain a valid alias configuration
> No description file found
> no extension
> Field 'browser' doesn't contain a valid alias configuration
> E:\Mayun\Hippy\packages\hippy-react-web doesn't exist
> .js
> Field 'browser' doesn't contain a valid alias configuration
> E:\Mayun\Hippy\packages\hippy-react-web.js doesn't exist
> .jsx
> Field 'browser' doesn't contain a valid alias configuration
> E:\Mayun\Hippy\packages\hippy-react-web.jsx doesn't exist
> .json
> Field 'browser' doesn't contain a valid alias configuration
> E:\Mayun\Hippy\packages\hippy-react-web.json doesn't exist
> as directory
> E:\Mayun\Hippy\packages\hippy-react-web doesn't exist
> i ｢wdm｣: wait until bundle finished: /

npm i  @hippy/react

**Comment by pengzhengang** [comment]
依赖都装了的&nbsp; 我直接npm&nbsp;i&nbsp;的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jerome han"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月6日(星期四) 晚上9:22
收件人:&nbsp;"Tencent/Hippy"<Hippy@noreply.github.com&gt;;
抄送:&nbsp;"Attitude°"<1553323446@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/Hippy] hippy-react运行报错 (#130)



 
@hippy/react
  
npm i @hippy/react

**Comment by pengzhengang** [comment]
> > Project is running at http://localhost:8080/
> > i ｢wds｣: webpack output is served from /
> > i ｢wds｣: Content not from webpack is served from E:\Mayun\Hippy\hippy-react\hippy-react-demo
> > × ｢wdm｣: ModuleNotFoundError: Module not found: Error: Can't resolve '@hippy/react' in 'E:\Mayun\Hippy\hippy-react\hippy-react-demo\src'
> > at factory.create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\Compilation.js:925:10)
> > at factory (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:401:22)
> > at resolver (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:130:21)
> > at asyncLib.parallel (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:224:22)
> > at E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\neo-async\async.js:2830:7
> > at E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\neo-async\async.js:6877:13
> > at normalResolver.resolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\webpack\lib\NormalModuleFactory.js:214:25)
> > at doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:213:14)
> > at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
> > at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), :15:1)
> > at resolver.doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7)
> > at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
> > at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), :15:1)
> > at hook.callAsync (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\Resolver.js:285:5)
> > at _fn0 (eval at create (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\tapable\lib\HookCodeFactory.js:33:10), :27:1)
> > at resolver.doResolve (E:\Mayun\Hippy\hippy-react\hippy-react-demo\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43)
> > × ｢wdm｣: resolve '@hippy/react' in 'E:\Mayun\Hippy\hippy-react\hippy-react-demo\src'
> > Parsed request is a module
> > using description file: E:\Mayun\Hippy\hippy-react\hippy-react-demo\package.json (relative path: ./src)
> > aliased with mapping '@hippy/react': 'E:\Mayun\Hippy\packages\hippy-react-web' to 'E:\Mayun\Hippy\packages\hippy-react-web'
> > using description file: E:\Mayun\Hippy\hippy-react\hippy-react-demo\package.json (relative path: ./src)
> > Field 'browser' doesn't contain a valid alias configuration
> > No description file found
> > no extension
> > Field 'browser' doesn't contain a valid alias configuration
> > E:\Mayun\Hippy\packages\hippy-react-web doesn't exist
> > .js
> > Field 'browser' doesn't contain a valid alias configuration
> > E:\Mayun\Hippy\packages\hippy-react-web.js doesn't exist
> > .jsx
> > Field 'browser' doesn't contain a valid alias configuration
> > E:\Mayun\Hippy\packages\hippy-react-web.jsx doesn't exist
> > .json
> > Field 'browser' doesn't contain a valid alias configuration
> > E:\Mayun\Hippy\packages\hippy-react-web.json doesn't exist
> > as directory
> > E:\Mayun\Hippy\packages\hippy-react-web doesn't exist
> > i ｢wdm｣: wait until bundle finished: /
> 
> npm i @hippy/react

npm i 转、

**Comment by jeromehan** [comment]
> 依赖都装了的&nbsp; 我直接npm&nbsp;i&nbsp;的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jerome han"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月6日(星期四) 晚上9:22 收件人:&nbsp;"Tencent/Hippy"<Hippy@noreply.github.com&gt;; 抄送:&nbsp;"Attitude°"<1553323446@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

![image](https://user-images.githubusercontent.com/19773879/73941397-29fa2400-4928-11ea-96a8-680a6a5cc302.png)
把这个下面的alias全部去掉，先注释了

**Comment by jeromehan** [comment]
> > 依赖都装了的  我直接npm i 的
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "jerome han"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年2月6日(星期四) 晚上9:22 收件人: "Tencent/Hippy"<[Hippy@noreply.github.com](mailto:Hippy@noreply.github.com)>; 抄送: "Attitude°"<[1553323446@qq.com](mailto:1553323446@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> ![image](https://user-images.githubusercontent.com/19773879/73941397-29fa2400-4928-11ea-96a8-680a6a5cc302.png)
> 把这个下面的alias全部去掉，先注释了



> 依赖都装了的&nbsp; 我直接npm&nbsp;i&nbsp;的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jerome han"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月6日(星期四) 晚上9:22 收件人:&nbsp;"Tencent/Hippy"<Hippy@noreply.github.com&gt;; 抄送:&nbsp;"Attitude°"<1553323446@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hippy-react-demo - scripts 下的alias全部干掉

**Comment by pengzhengang** [comment]
方便加下Q：1553323446&nbsp; 谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jerome han"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月6日(星期四) 晚上9:34
收件人:&nbsp;"Tencent/Hippy"<Hippy@noreply.github.com&gt;;
抄送:&nbsp;"Attitude°"<1553323446@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/Hippy] hippy-react运行报错 (#130)



  
依赖都装了的&nbsp; 我直接npm&nbsp;i&nbsp;的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jerome han"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月6日(星期四) 晚上9:22 收件人:&nbsp;"Tencent/Hippy"<Hippy@noreply.github.com&gt;; 抄送:&nbsp;"Attitude°"<1553323446@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  

 把这个下面的alias全部去掉，先注释了
   
依赖都装了的&nbsp; 我直接npm&nbsp;i&nbsp;的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jerome han"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月6日(星期四) 晚上9:22 收件人:&nbsp;"Tencent/Hippy"<Hippy@noreply.github.com&gt;; 抄送:&nbsp;"Attitude°"<1553323446@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
hippy-react-demo - scripts 下的alias全部干掉

**Comment by pengzhengang** [comment]
> > > 依赖都装了的  我直接npm i 的
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "jerome han"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年2月6日(星期四) 晚上9:22 收件人: "Tencent/Hippy"<[Hippy@noreply.github.com](mailto:Hippy@noreply.github.com)>; 抄送: "Attitude°"<[1553323446@qq.com](mailto:1553323446@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/19773879/73941397-29fa2400-4928-11ea-96a8-680a6a5cc302.png)
> > 把这个下面的alias全部去掉，先注释了
> 
> > 依赖都装了的  我直接npm i 的
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "jerome han"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年2月6日(星期四) 晚上9:22 收件人: "Tencent/Hippy"<[Hippy@noreply.github.com](mailto:Hippy@noreply.github.com)>; 抄送: "Attitude°"<[1553323446@qq.com](mailto:1553323446@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> hippy-react-demo - scripts 下的alias全部干掉


i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from E:\Mayun\Hippy\hippy-react\hippy-react-demo
‼ ｢wdm｣: Hash: c6437d3bcb260160b31f
Version: webpack 4.41.5
Time: 3737ms
Built at: 2020-02-06 22:12:05
                Asset      Size  Chunks                    Chunk Names
 assets/back-icon.png  2.12 KiB          [emitted]
hippy-react-demo.html  1.55 KiB          [emitted]
         index.web.js   430 KiB       0  [emitted]  [big]  index
Entrypoint index [big] = index.web.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 regenerator-runtime ./src/main.js 52 bytes {0} [built]
[./node_modules/@hippy/react/dist/index.js] 129 KiB {0} [built]
[./node_modules/ansi-html/index.js] 4.64 KiB {0} [built]
[./node_modules/regenerator-runtime/runtime.js] 23.7 KiB {0} [built]
[./node_modules/strip-ansi/index.js] 174 bytes {0} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {0} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {0} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {0} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {0} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {0} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {0} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {0} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {0} [built]
[./src/main.js] ./src/main.js + 39 modules 215 KiB {0} [built]
    | ./src/main.js 122 bytes [built]
    | ./src/app.jsx 4.75 KiB [built]
    | ./src/pages/gallery.jsx 10.3 KiB [built]
    | ./src/pages/debug.jsx 5.18 KiB [built]
    | ./src/shared/SafeAreaView.jsx 4.32 KiB [built]
    | ./src/utils.js 924 bytes [built]
    | ./src/components/index.js 591 bytes [built]
    | ./src/modules/index.js 421 bytes [built]
    | ./src/externals/index.js 189 bytes [built]
    | ./src/pages/back-icon.png 64 bytes [built]
    | ./src/components/Focusable/index.jsx 4.09 KiB [built]
    | ./src/components/Image/index.jsx 2.38 KiB [built]
    | ./src/components/ListView/index.jsx 9.31 KiB [built]
    | ./src/components/Modal/index.jsx 5.46 KiB [built]
    | ./src/components/RefreshWrapper/index.jsx 11.7 KiB [built]
    |     + 25 hidden modules
    + 29 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  index.web.js (430 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  index (430 KiB)
      index.web.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "hippy-react-demo.html":
     1 asset
    Entrypoint undefined = hippy-react-demo.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./scripts/template.html] 1.91 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 905 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {0} [built]
i ｢wdm｣: Compiled with warnings.

**Comment by xuqingkuang** [comment]
> > 依赖都装了的  我直接npm i 的
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "jerome han"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年2月6日(星期四) 晚上9:22 收件人: "Tencent/Hippy"<[Hippy@noreply.github.com](mailto:Hippy@noreply.github.com)>; 抄送: "Attitude°"<[1553323446@qq.com](mailto:1553323446@qq.com)>;"Author"<[author@noreply.github.com](mailto:author@noreply.github.com)>; 主题: Re: [Tencent/Hippy] hippy-react运行报错 (#130) @hippy/react npm i @hippy/react — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> ![image](https://user-images.githubusercontent.com/19773879/73941397-29fa2400-4928-11ea-96a8-680a6a5cc302.png)
> 把这个下面的alias全部去掉，先注释了

已经给出答案了。

在 Hippy 目录下编译一下 sdk 也可以。

或许我加个前端 sdk 如果没有编译就不用 alias 也可以。

**Comment by xuqingkuang** [comment]
补了个 #132，一是只在调试时才会开启本地 sdk 的 alias，二是就算没有本地 sdk 也能用 node_modules 里的。
