### ISSUE TITLE
Text ellipsizeMode非正常截断

### ISSUE THREAD

**Issue by yufengzhw** [Tencent/Hippy#133]
Text ellipsizeMode下，...后出现会出现大约一个中文字符宽度的空白。
在hippy-react-demo/src/components/Text/index.jsx  render中添加以下代码可以复现
'''
<View style={styles.itemContent}>
       <View style={[{flexDirection: 'row',width: 150,flexWrap: 'nowrap',alignItems: 'center'}]}>
            <Text numberOfLines={1} style={[styles.normalText, {flex: -1}]}>short words</Text>
            <View style={[{width: 16,height: 16,backgroundColor: '#ff0000'}]}></View>
        </View>
        <View style={[{flexDirection: 'row',width: 150,flexWrap: 'nowrap',alignItems: 'center'}]}>
            <Text numberOfLines={1} style={[styles.normalText, {flex: -1}]}>loooooong wooooooords</Text>
             <View style={[{width: 16,height: 16,backgroundColor: '#ff0000'}]}></View>
         </View>
</View>
'''

![code](https://puui.qpic.cn/vupload/0/1581575457851_6koxt0sq74f.png/0)
![screenshot](https://puui.qpic.cn/vupload/0/1581575489508_evy34uvpyad.png/0)
![online](https://puui.qpic.cn/vupload/0/1581575522014_njnep3mw2ze.png/0)

**Comment by jeromehan** [comment]
> Text ellipsizeMode下，...后出现会出现大约一个中文字符宽度的空白。
> 在hippy-react-demo/src/components/Text/index.jsx render中添加以下代码可以复现
> '''
> 
> <View style={[{flexDirection: 'row',width: 150,flexWrap: 'nowrap',alignItems: 'center'}]}>
> <Text numberOfLines={1} style={[styles.normalText, {flex: -1}]}>short words
> <View style={[{width: 16,height: 16,backgroundColor: '#ff0000'}]}>
> 
> <View style={[{flexDirection: 'row',width: 150,flexWrap: 'nowrap',alignItems: 'center'}]}>
> <Text numberOfLines={1} style={[styles.normalText, {flex: -1}]}>loooooong wooooooords
> <View style={[{width: 16,height: 16,backgroundColor: '#ff0000'}]}>
> 
> 
> '''
> 
> ![code](https://camo.githubusercontent.com/d534aa199d2c080ebcb92744de974d1be30af1f2/68747470733a2f2f707575692e717069632e636e2f7675706c6f61642f302f313538313537353435373835315f366b6f78743073713734662e706e672f30)
> ![screenshot](https://camo.githubusercontent.com/87e1fdcff38c7070d844fff1dd92cf1b8eee0273/68747470733a2f2f707575692e717069632e636e2f7675706c6f61642f302f313538313537353438393530385f65767933347576707961642e706e672f30)
> ![online](https://camo.githubusercontent.com/cb71c4b6da5398d0d7957828233e94dc3d15a568/68747470733a2f2f707575692e717069632e636e2f7675706c6f61642f302f313538313537353532323031345f6e6a6e6570336d77327a652e706e672f30)

经过在RN和hippy的ios实验，
![image](https://user-images.githubusercontent.com/19773879/74451163-2c292900-4eba-11ea-98f6-223b804350db.png)。问题一样，我猜测应该是ellipsizeMode:NSLineBreakByTruncatingTail在原生端本来就有这些问题。

**Comment by xuqingkuang** [comment]
> 问题一样，我猜测应该是ellipsizeMode:NSLineBreakByTruncatingTail在原生端本来就有这些问题。

嗯。。。不好说。

**Comment by jeromehan** [comment]
> > 问题一样，我猜测应该是ellipsizeMode:NSLineBreakByTruncatingTail在原生端本来就有这些问题。
> 
> 嗯。。。不好说。
同时对比微博和qq浏览器，都是这种情况
![image](https://user-images.githubusercontent.com/19773879/74496743-98397a80-4f16-11ea-9552-e3017756dbc1.png)
![image](https://user-images.githubusercontent.com/19773879/74496757-a38ca600-4f16-11ea-8c04-94a08361f187.png)

**Comment by jeromehan** [comment]
> > 问题一样，我猜测应该是ellipsizeMode:NSLineBreakByTruncatingTail在原生端本来就有这些问题。
> 
> 嗯。。。不好说。

![image](https://user-images.githubusercontent.com/19773879/74496922-231a7500-4f17-11ea-845a-c184f6d3f2b9.png)
此方法计算的文字实际长度会偏小，这是终端自带的。应该是没办法改变的

**Comment by xuqingkuang** [comment]
Seems solved, close it.
