### ISSUE TITLE
如何在App端 ,即安卓/ios的手机端,上使用原生 nodejs 的API?

### ISSUE THREAD

**Issue by masx200** [Tencent/Hippy#134]
**Is your feature request related to a problem? Please describe.**
如何在App端 ,即安卓/ios的手机端,上使用原生 nodejs 的API?
**Describe the solution you'd like**

目前在App端上能使用的API太少,会有插件市场吗？

原生开发对于前端入门开发人员来说难度太高了

在App端 的 提供的功能还不够用,很多的原生能力难以实现,而且nodejs的生态非常丰富

**Describe alternatives you've considered**

**Additional context**

**Comment by xuqingkuang** [comment]
你指的哪部分功能难度太高了？

腾讯做的高质量第三方插件会放在 https://github.com/hippy-contrib
不过既然是第三方就得一个个去谈劝他们对外开源，受到疫情影响这个可能要延误一段时间。

nodejs 的生态丰富也不打算采用，因为它主要面对的是服务器端，使用场景是不一样的，不过 npm 中很多生态是可以使用的。

**Comment by masx200** [comment]
目前hippy框架能够提供的api有点少了,隔壁uni-app至少还有html5plus的api可以用

https://www.html5plus.org/doc/h5p.html

**Comment by xuqingkuang** [comment]
> 目前hippy框架能够提供的api有点少了,隔壁uni-app至少还有html5plus的api可以用
> 
> https://www.html5plus.org/doc/h5p.html

hippy 跟 uniapp 的目标是不一样的，hippy 是开发终端 app 的，这部分扩展是终端根据需要自己扩展，hippy 可以通过终端代码做到更进一步的控制。而 hippy 自身只聚焦于核心和扩展能力，兼顾包体积和功能情况下，更多功能会让业务自己按照自己需求去使用而不是一揽子全部集成。

uniapp 目前依然是基于 webview 实现的，像长信息流列表（比如 QQ 浏览器首页信息流) 用 uniapp 根本没法做。

**Comment by masx200** [comment]
我还是希望插件生态能更丰富吧

**Comment by xuqingkuang** [comment]
> 我还是希望插件生态能更丰富吧

嗯，生态会慢慢好的，内部的 Lottie、SVG、GCanvas 等插件准备好了也会对外开源。

**Comment by xuqingkuang** [comment]
先 close
