### ISSUE TITLE
Whether to provide boxShadow and Filter:blur style?  是否可以提供框阴影和模糊滤镜？

### ISSUE THREAD

**Issue by Eden-Harris** [Tencent/Hippy#142]
**Is your feature request related to a problem? Please describe.**
> When rendering the list at that time, I very much wanted to use boxShadow to make the list-card more three-dimensional and beautiful;
Besides, when rendering the sliding card and or the list body, a Gaussian blur background will make the page more transparent.
>
>当渲染列表时，非常希望能够使用boxShadow来让list-card更加的立体，美观；另外在渲染滑动卡片和或列表主体时，有高斯模糊背景的话，会让页面更加的通透。

**Describe the solution you'd like**
> Use css style implementation, just like H5
> 
> 直接使用css样式编写，就行编写vue H5一样

**Describe alternatives you've considered**
> Consider providing conditional judgment. It can also be implemented using native controls using the respective platform.
>
> 希望可以考虑提供平台条件判断，使用各自平台使用原生控件来实现

**Comment by xuqingkuang** [comment]
阴影在开发中，近期会推出双端接口一致的阴影属性参数。

模糊目前在图片上有个 blurRadius 属性，但是仅限 iOS，Android 一起完成后再对外放出。

**Comment by xuqingkuang** [comment]
iOS 的阴影接口已经提交了 - https://github.com/Tencent/Hippy/pull/145

和 box-shadow 基本一致，hippy-vue 转一下就能跟 box-shadow 完全一样了。

**Comment by zoomchan-cxj** [comment]
[boxShadow完整使用说明](https://hippyjs.org/#/style/appearance?id=boxshadow)
