### ISSUE TITLE
何时添加webassembly模块的支持？

### ISSUE THREAD

**Issue by masx200** [Tencent/Hippy#144]
**Is your feature request related to a problem? Please describe.**
何时添加webassembly模块的支持？
**Describe the solution you'd like**
无法在hippy中调用其他可执行文件，进行高性能的计算。
**Describe alternatives you've considered**

**Additional context**

**Comment by xuqingkuang** [comment]
想想还是回复一下。

WASM  其实本质上也是用 C/C++ 来开发的，Hippy 已经提供了基于 C/C++ 的 Core 架构来实现相对应功能，基于此架构的绘图能力也在 3.0 实现。

这个可以做，但是恐怕优先级没那么高，WASM 其实那么多年下来也一直是不温不火的。

先 close 以后再说。
