### ISSUE TITLE
Android demo工程编译不过

### ISSUE THREAD

**Issue by wxCUHK** [Tencent/Hippy#1495]
**Describe the bug**
NDK已配置
C/C++: ld: error: /home/wx/workspace/Hippy/android/sdk/src/main/jni/third_party/v8/latest/official-release/libs/arm64-v8a/libv8_monolith.a:1: unknown directive: version

**Comment by zoomchan-cxj** [comment]
检查下是不是lfs没拉完整

**Comment by BraveAlan** [comment]
> 

您好，我也遇到了同样的问题，请问该如何解决？git lfs是在官网上直接下的，调用enable_lfs.sh脚本也是正常的，最后编译的时候出错了

**Comment by zoomchan-cxj** [comment]
> > 
> 
> 您好，我也遇到了同样的问题，请问该如何解决？git lfs是在官网上直接下的，调用enable_lfs.sh脚本也是正常的，最后编译的时候出错了

1. git lfs pull 确认lfs文件拉成功了
2. 升级一下AS版本

**Comment by BraveAlan** [comment]
> 

感谢回复！按照方法1编译成功了！
