### ISSUE TITLE
感觉不错，后期做几个界面试试，对比rn或者weex

### ISSUE THREAD

**Issue by quzhengping** [Tencent/Hippy#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dbl520** [comment]
对比下flutter，还可以就可以搞了

**Comment by xuqingkuang** [comment]
> 对比下flutter，还可以就可以搞了

可以的，有问题多交流。我在写一个综述和实战入门文档，稍后会放出来。

**Comment by Eden-Harris** [comment]
> > 对比下flutter，还可以就可以搞了
> 
> 可以的，有问题多交流。我在写一个综述和实战入门文档，稍后会放出来。

支持动态发布吗？

**Comment by quzhengping** [comment]
期待中

**Comment by cdll** [comment]
可以和flutter比比肩啊哈哈哈

**Comment by chenzhengxu** [comment]
原理上和Weex或者RN有很大差别吗，比这两个有什么优化的点？ @xuqingkuang

**Comment by hustcer** [comment]
通用组件貌似还不多啊？

**Comment by JeasonLaung** [comment]
flutter上手快，但累赘的太厉害了，虽然用起来也爽。因为直接可以改原生代码，刚刚看到视频进来的，不知道原生能力怎样，先支持一下！！！
