### ISSUE TITLE
请问 fullscreen 这个class的定义在哪里？

### ISSUE THREAD

**Issue by SaxonZhang2** [Tencent/Hippy#1534]
https://github.com/Tencent/Hippy/blob/befab2c9dcf6af296058454bdc86c8110db458bf/examples/hippy-vue-demo/src/components/native-demos/demo-dialog.vue#L24

**Comment by zoomchan-cxj** [comment]
目前由于hippy-vue 还不支持scoped，这个class在 https://github.com/Tencent/Hippy/blob/master/examples/hippy-vue-demo/src/app.vue#L93
