### ISSUE TITLE
建议对入门级小白更友好点，编译DEMO屏蔽对NDK依赖

### ISSUE THREAD

**Issue by kztao** [Tencent/Hippy#154]
小白，因业务需要，调研跨平台APP开发，看到Hippy特别高兴，想试试，编译个DEMO，两天没编译好，公司让放弃了...
特别希望DEMO的编译，能更简单点...

**Comment by jeromehan** [comment]
> 小白，因业务需要，调研跨平台APP开发，看到Hippy特别高兴，想试试，编译个DEMO，两天没编译好，公司让放弃了...
> 特别希望DEMO的编译，能更简单点...

仔细看一下android-demo README 会看到
如果一直报编译不过可以展示屏蔽掉sdk目录下面的build.gradle这个函数
buildNdkLibs(dependsOn: (ISCI.toBoolean() ? dealNdkLibSymbols : stripSO), type: Copy)
改为  buildNdkLibs( type: Copy) 这样只是不去编译c++代码

**Comment by xxs665** [comment]
可以使用这个脚手架，不过目前只支持mac版
https://www.npmjs.com/package/cra-template-hippy-react
