### ISSUE TITLE
ERROR: extensionSupplier.get()!!.compileSdkVersion must not be null

### ISSUE THREAD

**Issue by huoxiangdong** [Tencent/Hippy#16]
运行 android-demo 提示 ERROR: extensionSupplier.get()!!.compileSdkVersion must not be null

macOS 10.15.3
Android Studio 3.5.3

**Comment by xuqingkuang** [comment]
可能是 Gradle 的问题，编译 Hippy 注意一下不要更新 Toolchain，都是有对应版本的，否则可能会编译失败。

可以试一下，如果不行还请 @siguangli 来帮忙一起看看。

> 在开始前请确认好 SDK 和 NDK 都安装了范例的指定版本，**并且请勿更新编译工具链**。

[README.zh_CN.md](https://github.com/Tencent/Hippy/blob/master/README.zh_CN.md#%E5%90%AF%E5%8A%A8-android-app-%E6%9D%A5%E6%B5%8B%E8%AF%95-hippy-react-%E6%88%96%E8%80%85-hippy-vue-%E8%8C%83%E4%BE%8B)

**Comment by xuqingkuang** [comment]
As a long time no response, close it first.

**Comment by kassadin** [comment]
```
echo $ANDROIDNDK_LINUX_R10E
echo $ANDROIDNDK_LINUX_R9D
```
这种上古 SDK 应该已经绝版了…

**Comment by ldwonday** [comment]
实在无法运行。下载了最新的ndk里面的toolchains没有mips64el-linux-android！还是运行不了！

**Comment by sungerk** [comment]
+1

**Comment by ldwonday** [comment]
@sungerk 问题解决了，找到ndk的目录，去toolchains下面执行命令：`ln -sf aarch64-linux-android-4.9 mips64el-linux-android`就好啦！~

**Comment by sungerk** [comment]
> @sungerk 问题解决了，找到ndk的目录，去toolchains下面执行命令：`ln -sf aarch64-linux-android-4.9 mips64el-linux-android`就好啦！~记住不要升级gradle！

我试了下还是没有用

**Comment by ldwonday** [comment]
@sungerk 具体的首先你的as如果是3.0以上，as安装ndk会直接安装到ndk目录，你需要复制下这个ndk目录下的版本号目录下的文件到ndk-bundle目录，没有这个目录就新建一个，然后在这个ndk-bundle目录下执行那个命令！~

**Comment by weizhanzhan** [comment]
windows的怎么解决

**Comment by ldwonday** [comment]
@weizhanzhan window就找对应的命令去修改就好了！~一样的操作，记着是在ndk-bundle目录下执行！

**Comment by weizhanzhan** [comment]
> @weizhanzhan window就找对应的命令去修改就好了！~一样的操作，记着是在ndk-bundle目录下执行！

ln 是什么？我本地没有这个命令

**Comment by weizhanzhan** [comment]
@ldwonday ln 是什么？我本地没有这个命令

**Comment by ldwonday** [comment]
@weizhanzhan 相当于window的创建快捷方式的命令一样，就是一个快捷方式指向aarch64-linux-android-4.9！

**Comment by sungerk** [comment]
试了还是没用

**Comment by ldwonday** [comment]
@sungerk 你的gradle是否是2.3.3？
![image](https://user-images.githubusercontent.com/4630157/71508044-7da53680-28c1-11ea-9407-b89b656d759a.png)
![image](https://user-images.githubusercontent.com/4630157/71508058-88f86200-28c1-11ea-896f-5a9b21ac65ad.png)
b不是的话就改成2.3.3

**Comment by sungerk** [comment]
我用的是3.5.3

> @sungerk 你的gradle是否是2.3.3？
> ![image](https://user-images.githubusercontent.com/4630157/71508044-7da53680-28c1-11ea-9407-b89b656d759a.png)
> ![image](https://user-images.githubusercontent.com/4630157/71508058-88f86200-28c1-11ea-896f-5a9b21ac65ad.png)
> 不是的话就改成2.3.3

我用的是3.5.3

**Comment by ldwonday** [comment]
@sungerk 前面就已经给你讲了，不要升级你的gradle！~按照官方的gradle来！~

**Comment by weizhanzhan** [comment]
@ldwonday  我弄好之后报这个错 ERROR: Unable to find toolchain: C:\Users\zhanwei\AppData\Local\Android\Sdk\ndk-bundle\toolchains\mips64el-linux-android-lnk\prebuilt

**Comment by ldwonday** [comment]
@weizhanzhan 看我前面的回答，再看看报错，你有没有ndk-bundle这个目录？

**Comment by weizhanzhan** [comment]
> @weizhanzhan 看我前面的回答，再看看报错，你有没有ndk-bundle这个目录？

有的😀

**Comment by ldwonday** [comment]
@weizhanzhan  mips64el-linux-android-lnk， 咋多了一个lnk，你这个是什么鬼？最好找到ln在windows下对应的命令吧！

**Comment by gavinliu** [comment]
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
```

跑不起来呢，ndk 我都降到 16，还是哪儿还要配置？

**Comment by sungerk** [comment]
> ```
> CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
> CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> ```
> 
> 跑不起来呢，ndk 我都降到 16 了，还是哪儿还要配置？

俺也一样，cmake出错。

**Comment by ldwonday** [comment]
@gavinliu CMake的问题你需要在As里面的Sdk tools安装Cmake
![image](https://user-images.githubusercontent.com/4630157/71510837-30c65d80-28cb-11ea-96a5-ca6a7f8b4cb4.png)
另外需要安装Ninja，mac：`brew Ninja`，windows：下载[https://github.com/ninja-build/ninja/releases](https://github.com/ninja-build/ninja/releases)下载Ninja，然后解压，解压后设置下环境变量！

**Comment by ldwonday** [comment]
@sungerk NDK无需降级！Cmake的问题很好解决，按照我上面的方法！这些坑我都踩过了！

**Comment by gavinliu** [comment]
@ldwonday 
brew install ninja 搞定

**Comment by weizhanzhan** [comment]
@ldwonday  这个ninja是干嘛的 我现在这个错误是不是也是因为这个CMake Error: Could not create named generator Android Gradle - Ninja

**Comment by ldwonday** [comment]
@weizhanzhan 一个构建工具[https://blog.csdn.net/m0_37194132/article/details/86579287](https://blog.csdn.net/m0_37194132/article/details/86579287)
你这个错误明显不是没有安装Ninja，而是gradle的问题！

**Comment by ldwonday** [comment]
![image](https://user-images.githubusercontent.com/4630157/71511548-bf3bde80-28cd-11ea-9730-12f51f303cfc.png)

**Comment by ldwonday** [comment]
## 前言
Hippy是腾讯最近开源的一款跨平台的前端框架，一套代码即可运行与android、ios、和web！和weex、rn一样，不过腾讯这个Hippy而腾讯的 Hippy 框架，也是在上层兼容了 RN 的API。这意味着，如果你用 Hippy 构建了应用，又想要切回 RN 的时候，业务层的工作量是非常小的，几乎0成本。
## 开始
1. `clone https://github.com/Tencent/Hippy.git` 到webstorm或者vs中。
2. 安装前端依赖，运行命令：`npm install`。
3. 编译前端 SDK 包，运行命令： `npm run build`。
4. 选择一个前端范例项目来进行编译：npm run buildexample -- [hippy-react-demo|hippy-vue-demo]。

## 运行
启动 Xcode或者As并且导入根目录下的examples/ios-demo项目或者examples/android-demo项目，然后运行项目。
## 坑点
这里要说的是假如你的As版本在3.0以上，在安卓上运行可能会出现意想不到的问题，
比如：`No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android` 
或者 `extensionSupplier.get()!!.compileSdkVersion must not be null`
再或者 `CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
     CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
     CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage`
解决方案请参考：[https://github.com/Tencent/Hippy/issues/16](https://github.com/Tencent/Hippy/issues/16)

## 开发
对于web前端同学来说，`npm run serve`可以运行web版本，运行`npm run hippy:vendor` 和 `npm run hippy:build`可以生成native端的包，复制这个包到你android或者ios项目中的asset即可！

**Comment by jeromehan** [comment]
> > ```
> > CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
> > CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> > CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> > ```
> > 
> > 
> > 跑不起来呢，ndk 我都降到 16 了，还是哪儿还要配置？
> 
> 俺也一样，cmake出错。

整个流程请参考 https://github.com/Tencent/Hippy/issues/39#issuecomment-569419541
