### ISSUE TITLE
希望支持异步异常捕获

### ISSUE THREAD

**Issue by niuDazhuang** [Tencent/Hippy#1617]
**Is your feature request related to a problem? Please describe.**
<img width="716" alt="image" src="https://user-images.githubusercontent.com/24971720/157835841-f1c140cc-ed20-4fe3-b526-d6d37ff4822c.png">
现阶段不支持异步异常捕获
**Describe the solution you'd like**
实现类似node端的process.on('unhandledRejection', cb)，强化 hippy 错误监控能力

**Describe alternatives you've considered**

**Additional context**

**Comment by zoomchan-cxj** [comment]
iOS 当前可以采用 [polyfill](https://hippyjs.org/#/guide/exception?id=unhandledrejection) 的方式实现对promise unhandledrejection的处理
