### ISSUE TITLE
建议把介绍视频链接换成其他没广告的平台

### ISSUE THREAD

**Issue by Go7hic** [Tencent/Hippy#17]
一分半的视频介绍 ，半分钟的广告，  这谁顶得住呀， 上传到 B 站或者 youtube 都可以，不要放到腾讯视频上去。或者直接放个 MP4 的地址也可: https://ugccsy.qq.com/uwMROfz2r5zEIaQXGdGnC2dfDmafRkP9ujxgqKjuATzMrE-2/i3038urj2mt.mp4?sdtfrom=v1010&guid=c42d1f4d4179ccf324fdc83e10075a59&vkey=5ABEF01F985E474E5005F9F8C350AF6C20B3CA2E81C3212C930DF1D25C06784FBEF17738CBEB203C5EAF7441947EB618EE8DB68581159ED903F773522060352035E6B16D4E717A5F25E7DB1A53470578CF03F37EC721FF435660CF6FFF3D4313494649423094169E3A8F9B1323977E4F8499EAEC4392701B6BBC5F21FA818753

**Comment by imhazige** [comment]
真是讽刺，lol

**Comment by xuqingkuang** [comment]
这个确实有点尴尬，为了赶开源是先上传视频，然后才申请广告屏蔽的，刚刚从腾讯视频那里获得消息，屏蔽策略已经生效，或许现在已经可以了。

谢谢提出 issue。
