### ISSUE TITLE
AsyncStorage存储功能在iOS和安卓上表现不一致

### ISSUE THREAD

**Issue by yzclostboy** [Tencent/Hippy#170]
iOS的AsyncStorage存储针对项目做了存储隔离限制，不同项目之间不能共用，安卓是可以的。
希望iOS同安卓保持一致，做成app全局共用的。

**Comment by xuqingkuang** [comment]
是共用还是隔离，其实还有待讨论的，从安全角度来说，隔离可能更加符合实际情况。
