### ISSUE TITLE
ubuntu18.04 git clone不下来，压缩包也下载不下来

### ISSUE THREAD

**Issue by RyanChent** [Tencent/Hippy#173]
如题，想在系统为ubuntu的环境下看看该框架，一直下不下来，请问是什么原因呢

**Comment by xuqingkuang** [comment]
国内访问 Github 不太稳定，可以使用腾讯云的代码镜像的，它始终保持跟 Github 的同步更新。

https://git.code.tencent.com/Tencent_Open_Source/Hippy

**Comment by RyanChent** [comment]
好的，谢谢，就在之前用在码云上down下来了，多谢
