### ISSUE TITLE
输入框太多bug了？

### ISSUE THREAD

**Issue by zhazhaxia** [Tencent/Hippy#177]
1. 只能输入string，int无效
2 不会自动触发blur
3,。 设定宽高边框才展示，有效？
4 ios下展示问题
5. 内置函数getValue为什么要返回个promise？

辛苦开发同事帮忙看看哈，开发个input功能花了一整天。。。。

**Comment by xuqingkuang** [comment]
> 只能输入string，int无效

type 有 int 吗？目前支持 text、number、password 等。

> 不会自动触发blur
终端限制，范例有写怎么处理这种情况 - https://github.com/Tencent/Hippy/blob/master/examples/hippy-vue-demo/src/components/demos/demo-input.vue#L77

> 设定宽高边框才展示，有效？

依然算是个限制，跟浏览器不一样，浏览器里能够按照文字高度自动设置，而且有个默认宽度，这个已经修好了。

>  ios下展示问题

什么问题？

> 内置函数getValue为什么要返回个promise？

所有跟终端交互的都是异步，返回 Promise 是为了可以在前面加  await 让开发者更加方便一点。

**Comment by zhazhaxia** [comment]
> > 只能输入string，int无效
> 
> type 有 int 吗？目前支持 text、number、password 等。
> 
> > 不会自动触发blur
> > 终端限制，范例有写怎么处理这种情况 - https://github.com/Tencent/Hippy/blob/master/examples/hippy-vue-demo/src/components/demos/demo-input.vue#L77
> 
> > 设定宽高边框才展示，有效？
> 
> 依然算是个限制，跟浏览器不一样，浏览器里能够按照文字高度自动设置，而且有个默认宽度，这个已经修好了。
> 
> > ios下展示问题
> 
> 什么问题？
> 
> > 内置函数getValue为什么要返回个promise？
> 
> 所有跟终端交互的都是异步，返回 Promise 是为了可以在前面加 await 让开发者更加方便一点。

thx for your reply .
稍后我们整理一份我们遇到的问题还有ui相关问题哈。[握手]

**Comment by xuqingkuang** [comment]
好的，编辑一下正文，详细描述一下就好。

**Comment by zhazhaxia** [comment]
thx for your reply
晚点我们整理一份哈。
&nbsp;

吴俊辉
电话13580330270
邮箱zhazha_milu@qq.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XQ Kuang"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 晚上6:50
收件人: "Tencent/Hippy"<Hippy@noreply.github.com&gt;; 
抄送: "俊辉"<337262356@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/Hippy] 输入框太多bug了？ (#177)



只能输入string，int无效
  type 有 int 吗？目前支持 text、number、password 等。
  不会自动触发blur
 终端限制，范例有写怎么处理这种情况 - https://github.com/Tencent/Hippy/blob/master/examples/hippy-vue-demo/src/components/demos/demo-input.vue#L77
   设定宽高边框才展示，有效？
  依然算是个限制，跟浏览器不一样，浏览器里能够按照文字高度自动设置，而且有个默认宽度，这个已经修好了。
  ios下展示问题
  什么问题？
  内置函数getValue为什么要返回个promise？
  所有跟终端交互的都是异步，返回 Promise 是为了可以在前面加await 让开发者更加方便一点。

**Comment by zhazhaxia** [comment]
> 好的，编辑一下正文，详细描述一下就好。

请问下，blur的处理有react的demo吗？

**Comment by xuqingkuang** [comment]
> > 好的，编辑一下正文，详细描述一下就好。
> 
> 请问下，blur的处理有react的demo吗？

暂无，跟浏览器一样，直接用 ref 拿到节点后 blur() 就行。

例如：

```
<TextInput ref={ref => this.input = ref;} />

this.input.blur();
```

**Comment by zhazhaxia** [comment]
这个有兼容问题，Android下不行，另外还有个给的接口hideInputMethod也不行，也有兼容问题。不过这里我解决了，后续整理下input遇到的问题发你下&nbsp;

吴俊辉
电话13580330270
邮箱zhazha_milu@qq.com


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XQ Kuang"<notifications@github.com&gt;; 
发送时间: 2020年3月17日(星期二) 中午11:11
收件人: "Tencent/Hippy"<Hippy@noreply.github.com&gt;; 
抄送: "俊辉"<337262356@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/Hippy] 输入框太多bug了？ (#177)



好的，编辑一下正文，详细描述一下就好。
  请问下，blur的处理有react的demo吗？
  暂无，跟浏览器一样，直接用 ref 拿到节点后 blur() 就行。
 例如：
 <TextInput ref={ref =&gt; this.input = ref;} /&gt;this.input.blur();

**Comment by xuqingkuang** [comment]
blur() 的问题在 2.0.2 里应该已经修好了，先关闭本 issue，有别的问题请单独发一下。

多谢！

**Comment by zhazhaxia** [comment]
好的，感谢
