### ISSUE TITLE
when we can open source the part of hippybridge.so

### ISSUE THREAD

**Issue by tomzhang** [Tencent/Hippy#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tomzhang** [comment]
why the part of hippybridge is binary code? when we can open source of the source code?

**Comment by churchill-zhang** [comment]
The code in the core directory is the source code of hippybridge

**Comment by xuqingkuang** [comment]
> why the part of hippybridge is binary code? when we can open source of the source code?

YES，as @churchill-zhang said, the source code of `hippybridge.so` is located at https://github.com/Tencent/Hippy/tree/master/core

After the sdk compiled you will see the so is updated.

**Comment by tomzhang** [comment]
thanks
