### ISSUE TITLE
假如考虑在 Fragment 里面使用，可行？

### ISSUE THREAD

**Issue by syxc** [Tencent/Hippy#1852]
如题，不一定合理，但要是支持的话~

**Comment by zoomchan-cxj** [comment]
请详细描述你的需求是什么，Fragment是指的什么

**Comment by syxc** [comment]
> 请详细描述你的需求是什么，Fragment是指的什么

是这么回事，现在 Hippy 一般是在一个 Activity 里边初始化，使用嘛，在 Fragment 里边这么去用的话，我试过，现在不行。

**Comment by syxc** [comment]
> 请详细描述你的需求是什么，Fragment是指的什么

我说的这个是在 Android 里边。

**Comment by zoomchan-cxj** [comment]
@siguangli 看一下吧

**Comment by syxc** [comment]
请问这个 issue 反馈的问题，目前适配进度如何？

**Comment by syxc** [comment]
> @siguangli 看一下吧

请问这个 issue 反馈的问题，目前适配进度如何？
