### ISSUE TITLE
No type or protocol named 'UIWindowSceneDelegate'

### ISSUE THREAD

**Issue by HuangZhe007** [Tencent/Hippy#19]
使用mac编译ios环境，按照文档上面步骤xcode编译发生以下错误
No type or protocol named 'UIWindowSceneDelegate'

**Comment by HuangZhe007** [comment]
xcode 10跟这个有关系吗

**Comment by xuqingkuang** [comment]
> xcode 10跟这个有关系吗

应该没关系 @ozonelmy 来帮忙看一下吧

**Comment by HuangZhe007** [comment]
![image](https://user-images.githubusercontent.com/45168628/71435719-36823e80-2725-11ea-8143-c6ad31ab7bb0.png)

**Comment by HuangZhe007** [comment]
我升级了xcode11成功了

**Comment by ozonelmy** [comment]
UIWindowSceneDelegate是ios13引入的SDK。所以必须使用ios13以上的sdk编译。
