### ISSUE TITLE
[Feature request] Merge node operations to avoid unnecessary UIManager calls

### ISSUE THREAD

**Issue by boxizen** [Tencent/Hippy#199]
**Is your feature request related to a problem? Please describe.**
When a component is inserted into the page, especially in the case of ListView, the renderer will have **multiple calls of insertChild**,  which creates additional overhead and may have a **negative impact on FPS**.

**Describe the solution you'd like**
Merge multiple consecutive createNode operations while keeping the order of createNode updateNode and deleteNode unchanged.

**Describe alternatives you've considered**
When triggering node operations, first push the nodes which will be updated into the array, then separate and integrate the nodes in the microtask stage. Finally, perform a batch insert operation on the integrated node array

**Additional context**
![image](https://user-images.githubusercontent.com/6027456/77823555-fb821380-7136-11ea-9b01-defb3dba0c86.png)

In the case of sliding ListView (Statistics from [perfdog](https://perfdog.qq.com/)):

|  FPS |  Before  | Merged  |
|  ---- |  ----  | ----  |
| Avg  | 48.8  | 52.15  |
| Max  | 57.9 | 58.9 |

**Comment by xuqingkuang** [comment]
Thank you for your patch.

But could you have an investigation for the optimization patch? Why merge the `insertChild` will makes the fps higher?

The points:

1. There is a similar queue like `__batchNodes` in the native, the UIManagerModule operations will append actions into the queue, then flush when endBatch executed. In fact, hippy-react should submit the UI operations as soon.
2. The fps should be affected by the native, not hippy-react.
