### ISSUE TITLE
Android 自定义组件 imageView 宽高问题

### ISSUE THREAD

**Issue by youmu178** [Tencent/Hippy#216]
因为vue 得img 必须要设置宽高，所以
在Android 自定义组件 瀑布流imageview 在设置
android:layout_width="match_parent"
android:layout_height="wrap_content"
图片无法自适应。
可不可以在vue 中也可以自适应呢？

**Comment by xuqingkuang** [comment]
可以尝试一下用 `position: absolute; top: 0; right: 0; bottom: 0; left: 0` 让 img 自动设置尺寸。

**Comment by youmu178** [comment]
> 可以尝试一下用 `position: absolute; top: 0; right: 0; bottom: 0; left: 0` 让 img 自动设置尺寸。

`<div class="display-flex flex-column shop-introduce">
            <ul numberOfRows="10">
              <li v-for="img in 10" :key="img" type="introduce-img">
                
                <img class="introduce-img" src="https://minifanka.oss-cn-beijing.aliyuncs.com/gallery/6.1-1585792868836.png" />
              </li>
            </ul>
          </div>`
`.shop-introduce {
    margin-top: 10px;
    margin-left: 15px;
    margin-right: 15px;
    // height: 200px;
    // background-color: #dec096;
    .introduce-img {
      // flex: 1;
      position: absolute;
      right: 0px;
      left: 0px;
      top: 0px;
      bottom: 0px;
      resize-mode: cover;
      // height: 200px;
    }
  }`

你好尝试position: absolute; top: 0; right: 0; bottom: 0; left: 0，没有起作用

**Comment by youmu178** [comment]
> 可以尝试一下用 `position: absolute; top: 0; right: 0; bottom: 0; left: 0` 让 img 自动设置尺寸。



`    
 <div class="display-flex flex-column shop-introduce">

            <ul numberOfRows="10">
              <li v-for="img in 10" :key="img" type="introduce-img">
                <img class="introduce-img" src="https://minifanka.oss-cn-beijing.aliyuncs.com/gallery/6.1-1585792868836.png" />
              </li>
            </ul>
          `

`.shop-introduce {

    margin-top: 10px;
    margin-left: 15px;
    margin-right: 15px;
    .introduce-img {
      // flex: 1;
      position: absolute;
      right: 0px;
      left: 0px;
      top: 0px;
      bottom: 0px;
      resize-mode: cover;
      // height: 200px;
    }
  }
`
尝试使用position: absolute; top: 0; right: 0; bottom: 0; left: 0 不起作用

**Comment by xuqingkuang** [comment]
<img> 外面再套层 <div> 呢？

ul 和 li 其实不是特别标准的 div，前者负责滚动，后者负责被回收。简单说就是部分样式在它们两个上其实用不了，甚至可能不会参与渲染。

**Comment by youmu178** [comment]
> img 外面再套层 div 呢？
> 
> ul 和 li 其实不是特别标准的 div，前者负责滚动，后者负责被回收。简单说就是部分样式在它们两个上其实用不了，甚至可能不会参与渲染。

我现在换成了div，还是不行，请你帮帮我

```
data() {
    return {
      imgsList: [
        'https://minifanka.oss-cn-beijing.aliyuncs.com/gallery/1111-1585728468099.jpg',
        'https://minifanka.oss-cn-beijing.aliyuncs.com/shop-logo/110587.jpg',
        'https://xfkapi.ckhlw.cn/wxapi/goods/getQrcode?type=h5&goodsId=652&accessToken=',
        'https://minifanka.oss-cn-beijing.aliyuncs.com/gallery/1-1585728612992.png'
      ]
    };
  },
```
```
<div class="introduce-div">
  <div class="introduce-img-div" v-for="img in imgsList" :key="img.id">
     <div>
        <img class="introduce-img" :src="img" />
      </div>
 </div>
</div>
```
```
.introduce-div {
      // position: absolute;
      // right: 0px;
      // left: 0px;
      // top: 0px;
      // bottom: 0px;
      flex: 1;
      .introduce-img-div {
        flex: 1;
      }
      .introduce-img {
        flex: 1;
        position: absolute;
        right: 0px;
        left: 0px;
        top: 0px;
        bottom: 0px;
        resize-mode: cover;
      }
    }
```
