### ISSUE TITLE
Task 'wrapper' not found in project ':example'

### ISSUE THREAD

**Issue by BraveAlan** [Tencent/Hippy#2218]
我按照github上的教程，执行到第三步的时候：
![8172882BB81F78D9BE669388D262F218](https://user-images.githubusercontent.com/29628110/178212585-02a7c343-5f60-4841-b868-d15fb046697e.jpg)

Android studio 上出现如下错误，请问该怎么解决？
![9305D5BD347A20CAE8D2DD9A55254DF5](https://user-images.githubusercontent.com/29628110/178212637-21364350-766b-44ae-9b0a-222d6694c6e0.jpg)

**Comment by jiangfw** [comment]
我这样解决的问题
1.使用最新的AndroidStudio版本，Android Studio Chipmunk | 2021.2.1 Patch 1
2.导入工程的时候，直接导入Hippy路径，如下图：
<img width="369" alt="image" src="https://user-images.githubusercontent.com/12828194/178642491-198c96e8-b570-4d65-b97d-674824d0e2dc.png">

**Comment by BraveAlan** [comment]
感谢解答:)

**Comment by zoomchan-cxj** [comment]
readme 文档已经修改

**Comment by GrubbyHunter** [comment]
这个官网没改哦，导致我也卡半天
![image](https://user-images.githubusercontent.com/8695052/183019430-920f2993-c8b9-47aa-a68d-9af35dadb664.png)
