### ISSUE TITLE
modal例子错误

### ISSUE THREAD

**Issue by lxjwlt** [Tencent/Hippy#236]
**Describe the bug**
https://github.com/Tencent/Hippy/tree/master/examples/hippy-react-demo/src/components/Modal
modal这个代码示例是错误的，写错Text组件的示例了

**To Reproduce**

https://github.com/Tencent/Hippy/tree/master/examples/hippy-react-demo/src/components/Modal
modal这个代码示例是错误的，写错Text组件的示例了

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

**Comment by xuqingkuang** [comment]
回头会用 hippy-react-demo 用 react hooks 重写的，接口文档参考官网就行。

多份文档维护不过来，回头范例项目中的文档会全部删掉。
