### ISSUE TITLE
hippy-vue 的readme里的架构图无法查看

### ISSUE THREAD

**Issue by SaxonZhang2** [Tencent/Hippy#2396]
**Describe the bug**
图片无法查看：
https://github.com/Tencent/Hippy/blob/master/docs/hippy-vue/introduction.md
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/9671186/184472363-fdb8a9a5-cb05-4c79-95b4-81e86a6d4f24.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

**Comment by zoomchan-cxj** [comment]
请在官网里[对应位置](https://hippyjs.org/#/hippy-vue/introduction)，这是官网的源码
