### ISSUE TITLE
动态加载

### ISSUE THREAD

**Issue by zhazhaxia** [Tencent/Hippy#240]
请问hippy支持动态加载吗？或者动态加载包有什么方案吗？比如我要动态加载路由。
有没有思路呢？

**Comment by xuqingkuang** [comment]
这个需要终端同学参与的。

需要做一个模块，需要加载别的 js 包的把地址作为参数去 callNative 它的一个加载方法，它去加载那个地址的 js 包，并且启动一个新的 Hippy 引擎去加载。上下历史栈也需要那个模块进行维护。

我比较推荐维护一个业务包列表，终端启动时去加载它并且检查所有 js 包的版本情况，把新版都直接下载到本地，启动时直接从本地的 js 包启动。

---------

以上仅限 Android 操作系统。

**Comment by zhazhaxia** [comment]
感谢提供思路

**Comment by lazh** [comment]
动态加载还能再具体一点么，我现在也在看动态加载这一块，但是发现无法重复加载同一个js Bundle文件
