### ISSUE TITLE
dialog组件在部分vivo Android8.1机型上无法覆盖状态栏

### ISSUE THREAD

**Issue by consonluo** [Tencent/Hippy#244]
**Describe the bug**
dialog组件在部分vivo Android8.0机型上无法覆盖状态栏，导致加蒙层之后蒙层没有覆盖状态栏，其他机型没有问题

**Screenshots**
![ycf827935f11c973be01bf0edae4e1e5c1d05aae3dc7558ebfbeeffe28aca7e1ce912708ffb4d1516fea061ce4390f6d179a5b86bfee3b7c9b424974ac74ed1f9de2816b3e7d435543](https://user-images.githubusercontent.com/4338278/80566521-c0208080-8a25-11ea-9101-2de6d917239d.png)

- Device:
手机机型：Vivo Y85A 手机CPU（核）：8 手机内存（MB）：4096 系统版本： 8.1 
手机机型：Vivo Y97 全网通 手机CPU（核）：8 手机内存（MB）：4096 系统版本： 8.1 
手机机型：Vivo Y83A 手机CPU（核）：8 手机内存（MB）：4096 系统版本： 8.1 
手机机型：Vivo Y93 手机CPU（核）：8 手机内存（MB）：4096 系统版本： 8.1 
**Additional context**

**Comment by xuqingkuang** [comment]
可以看一下 QQ 浏览器，上面 Tab 列表，滚到最右边，会出现一个三条杠的圆形按钮，按一下它会有个弹窗。

看一下它的情况
