### ISSUE TITLE
使用navigator 获取用户位置

### ISSUE THREAD

**Issue by tweikiang** [Tencent/Hippy#246]
**Is your feature request related to a problem? Please describe.**
尝试了直接使用 navigator. geolocation 获取位置信息， 在web 版本，基本上都没问题，在Vue， iOS 和 安卓都不行

**Describe the solution you'd like**
直接、间接使用 navigator 所有功能 (vue)

**Additional context**
web 里
![Screenshot 2020-05-06 at 8 06 54 AM](https://user-images.githubusercontent.com/949345/81127381-9c52c280-8f70-11ea-82dc-c7ca1cc9daa6.png)

vs

ios emulator (native)
![Screenshot 2020-05-06 at 8 06 48 AM](https://user-images.githubusercontent.com/949345/81127397-a7a5ee00-8f70-11ea-880b-6fd3d257d3ee.png)

**Comment by xuqingkuang** [comment]
这个需要终端层支持的，Hippy 里其实没有  navigator 的。

**Comment by tweikiang** [comment]
hippy 现有什么组件可以获取用户位置， 打开相机， 打开文件等 ？
