### ISSUE TITLE
hippy现在还不支持fixed定位， 请问现在怎么处理fixed定位的case

### ISSUE THREAD

**Issue by durio61** [Tencent/Hippy#2464]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

**Comment by zoomchan-cxj** [comment]
将view提到最外层，用absolute来处理
