### ISSUE TITLE
NSData byte接口并不会一定返回带ending的char*字符串，这可能会导致传入的js执行非预期或执行失败

### ISSUE THREAD

**Issue by rhythmkay** [Tencent/Hippy#253]
`JSStringRef execJSString = jscWrapper->JSStringCreateWithUTF8CString((const char *)script.bytes);`

JSStringCreateWithUTF8CString这个接口这里使用有问题。
[NSData bytes]接口返回的是void*，而非char*，并且由于拷贝的问题，这个bytes一般会比实际的传入的要长，即可能不存在0x0结尾或者在非预期的length处结尾。
这会导致待执行的js有可能异常。

**Comment by ozonelmy** [comment]
所有Data使用之前已经通过loadPossiblyBundledApplicationScript添加结束字符
