### ISSUE TITLE
css style: background-image  , How to bind backgroundImage with variable.

### ISSUE THREAD

**Issue by humbass** [Tencent/Hippy#265]
**Describe the bug**

```javascript
<div :style="{height: 300, width: 500, 'background-image': 'url('+imgs.logo+')'}"></div>

data() {
    return {
      imgs: {
         logo
      }
   }
}
```

==== but below is work ====
```
<div class="bg" ></div>
.bg {
  height: 300;
  width: 500;
  background-image: url('http://192.168.120.143:8000/downloads/fengmian/label/img1.jpg')
}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [XiaoMi CC9]
- OS and version: [Android 1.0]
- Hippy native SDK version: [Lastest]
- Front-end SDK and version [@hippy/vue 2.0.1]

**Comment by xuqingkuang** [comment]
The following code just fine for current versions.

```javascript
:style="{height: 300, width: 500, 'background-image': imgs.logo}"
```

The inline background image style will support soon.
