### ISSUE TITLE
No component found for view with name "MyView" error on iOS simulator

### ISSUE THREAD

**Issue by erichua23** [Tencent/Hippy#27]
**Describe the bug**
In my ios simulator(iPhone 11 Max Pro), when I press the “View 组件” button on the demo's home page, this error appear.

**To Reproduce**
0. clone the Hippy repo. cd to `./Hippy/`
1. Install the dependencies with npm install.
2. Build the front-end sdk packages with npm run build.
3. Choose a demo to build with npm run buildexample -- [hippy-react-demo|hippy-vue-demo].
4. Start the Xcode and build the iOS app with open examples/ios-demo/HippyDemo.xcodeproj
5. Press the “View 组件” button on the demo's home page

**Expected behavior**
No error & no red screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1309744/71445986-b924f100-2759-11ea-8851-60c0a7cd36d0.png)

**Smartphone (please complete the following information):**
 - Device: simulator(iPhone 11 Max Pro)
 - OS and version: 13.3
 - Hippy native SDK version: (github master HEAD b7837fedbec9ec24068f0aa482ad5a97afa9acd6)
 - Front-end SDK and version (github master HEAD b7837fedbec9ec24068f0aa482ad5a97afa9acd6)

**Comment by xuqingkuang** [comment]
It's a known issue.

MyView is a customized component demo, implemented in [Android demo](https://github.com/Tencent/Hippy/tree/master/examples/android-demo/example/src/main/java/com/tencent/mtt/hippy/example/view)

But no iOS demo implementation yet, just dismiss it.
