### ISSUE TITLE
v-if 插入位置错误

### ISSUE THREAD

**Issue by franklinfee** [Tencent/Hippy#270]
```html
<div v-if="bool" class="first">
    <div />
</div>
<div class="container" />
<div v-if="!bool" class="last">
    <div />
</div>
```

当 `this.bool` 由 `false` 变为 `true` 时，`.first` 节点会被插入至 `.container` 的后面而非前面

**Comment by xuqingkuang** [comment]
目前只有 createNode，而没有 insertBefore，这种维持中间顺序的可能是有问题，Vue 会先创建新节点再删除旧节点，期间索引号可能会不符合预期。我一会儿看看。

可以先用 v-show 固定好渲染顺序在改变 bool 保证顺序一致。

**Comment by humbass** [comment]
这样操作肯定不行。要么用v-show, 要么加上z-index

**Comment by zoomchan-cxj** [comment]
测试过，没有出现描述的现象
