### ISSUE TITLE
请问如何支持canvas渲染

### ISSUE THREAD

**Issue by ljianc** [Tencent/Hippy#2701]
想在安卓端接入[echarts（js图表库）](https://echarts.apache.org/zh/index.html) 

小程序端是基于微信提供的CanvasRenderingContext2D实现的，
现在想做安卓端 （不想嵌webview），如果用hippy, 能实现吗？目前有没有能用于hippy的CanvasRenderingContext2D库？

**Comment by zoomchan-cxj** [comment]
可以基于类似的库来实现，如[skia canvas](https://skiacanvas.pages.woa.com/)
