### ISSUE TITLE
event.stopPropogation is not a function

### ISSUE THREAD

**Issue by December08** [Tencent/Hippy#2734]
在我们的app中有使用到"@hippy/react": "2.12.0"，并在新项目中使用了stopPropogation【2.11.2 版本开始包含的方法】，但是该方法会在安卓低版本app中出现『event.stopPropogation is not a function』这个问题，想了解下可能的原因有哪些，是低版本app的问题么？

**Comment by zoomchan-cxj** [comment]
这个方法只跟js sdk有关，是不是调试和非调试用的不同的包
