### ISSUE TITLE
目前腾讯内部哪些场景用了Hippy

### ISSUE THREAD

**Issue by seakop** [Tencent/Hippy#282]
看介绍腾讯内部18款APP是使用了Hippy，具体是什么业务场景使用，使用规模如何。谢谢

**Comment by haoran12138** [comment]
介绍里写的有  这里也有视频  https://v.qq.com/x/page/i3038urj2mt.html

**Comment by xuqingkuang** [comment]
轻插一下，手机QQ 8.3.9 版也内置了 Hippy 了。

**Comment by xxs665** [comment]
心悦俱乐部有不少页面是用hippy做的。可以看一下首页、指挥官、角色交易等

**Comment by seakop** [comment]
@haoran12138 @xuqingkuang @xxs665  非常感谢，我去体验体验
