### ISSUE TITLE
iOS手动集成文档过旧有大量错误，这里提供正确的集成说明请参考

### ISSUE THREAD

**Issue by CharlinFeng** [Tencent/Hippy#2915]
hippy手动集成：

1. 将core,sdk两个文件夹拖拽到项目。
（1）到build settings里面找到search path下设置Header Search Path值为"$(SRCROOT)/core" recursive（注意拖拽后的相对目录是否正确）
"$(SRCROOT)/sdk" none-recursive（注意拖拽后的相对目录是否正确）
(2) 到Build Phases/Copy Bundle Resources删除重复的CMakeList.txt和.clang-format，各种保留一份即可。
(3) 删除sdk/HippyLibrary.xcodeproj文件

2. 删除core/include/core/napi/v8目录
3. 删除core/src/napi/v8目录
4. 删除所有的adr目录（安卓系统使用）
5. inspector 有v8和jsc之分。需要对应引入jsc的inspector

**Comment by 0xDarker** [comment]
到了第5步，编译还是有一大堆错误

**Comment by wwwcg** [comment]
Thanks for feedback, we are updating the docs here

**Comment by wwwcg** [comment]
#3080
