### ISSUE TITLE
安卓textinput在点击“搜索”后，输入框失去焦点，但是键盘没收起来

### ISSUE THREAD

**Issue by baiyushiwhite** [Tencent/Hippy#296]
安卓textinput在点击“搜索”后，输入框失去焦点，但是键盘没收起来，即使手动调用blur和hideInputMethod也没有办法收起，导致退出页面键盘依然停在界面上
step1:
![image](https://user-images.githubusercontent.com/7857210/86091148-f938a800-badd-11ea-997b-50858f56572a.png)
step2:点击下一步，输入框失去焦点。但是键盘没有收起
![image](https://user-images.githubusercontent.com/7857210/86091191-09508780-bade-11ea-9534-d1ef7935098a.png)

sdk: 2.0.2

代码如下：

![image](https://user-images.githubusercontent.com/7857210/86091407-73692c80-bade-11ea-8094-c9642a1ffd50.png)

**Comment by zhazhaxia** [comment]
这个要手动触发input editableEnable的，属于hippy下的一个bug。需要手动兼容下

**Comment by zoomchan-cxj** [comment]
目前没有发现这个问题
