### ISSUE TITLE
测试用例写错了。。。

### ISSUE THREAD

**Issue by BarryfwuTencent** [Tencent/Hippy#2967]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

https://github.com/Tencent/Hippy/blob/master/android/sdk/src/test/java/com/tencent/mtt/hippy/utils/UrlUtilsTest.java
测试用例中 URL_HTTP 构造有问题，后面的4个测试用例有2个跑不过，把 s 去掉吧。

**Comment by iPel** [comment]
fixed with #2968
