### ISSUE TITLE
编译有问题

### ISSUE THREAD

**Issue by BarryfwuTencent** [Tencent/Hippy#2969]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**
默认编译配置中，安卓的 lintdedug 回检测几个 bug 并中断编译。建议在 android/sdk/build.gralde 文件中关闭掉 android.lintdebug.

android {
  lintOptions {
        checkReleaseBuilds false
        //If you want to continue even if errors found use following line
        abortOnError false
  }
  archivesBaseName = ARCHIVES_BASE_NAME
  compileSdkVersion COMPILE_VERSION as int

<img width="1081" alt="企业微信截图_f31975d6-450e-4bf2-8e79-4681a2cbbfc7" src="https://user-images.githubusercontent.com/98068256/220853966-5c65b0d5-5518-4b28-8a9d-77ad8b30544b.png">

**Comment by iPel** [comment]
不建议关闭lint能力，具体lint错误稍后修复
