### ISSUE TITLE
可以考虑建个官方群什么的

### ISSUE THREAD

**Issue by fulus06** [Tencent/Hippy#30]

**Comment by xuqingkuang** [comment]
QQ 群吗？其实有个微信群，但已经超过100人还得邀请了，还有500人上限。

**Comment by dbl520** [comment]
微信dbl2239146847拉一下

**Comment by 97zhaodashuai** [comment]
微信 zhaodsh 拉一下 谢谢

**Comment by todayliu** [comment]
微信Leo7891011 ，麻烦您了

**Comment by fulus06** [comment]
fushilu06，麻烦了。 @xuqingkuang  这样看来还是QQ群好用啊

**Comment by weizhanzhan** [comment]
weizhan675398552麻烦拉一下，谢谢

**Comment by tt990218** [comment]
tt2511590093  我们公司马上要开发 app 端了

**Comment by duanpengcheng520** [comment]
@xuqingkuang 麻烦了，拉一下duanpengcheng244

**Comment by xuqingkuang** [comment]
@duanpengcheng520 @tt990218 @weizhanzhan @fulus06 @todayliu @97zhaodashuai @dbl520 建了个 2000 人的 QQ 大群，一起来加吧。

**Comment by anthhub** [comment]
我也想加群

**Comment by gavanx** [comment]
微信MingooX，求拉

**Comment by tankxie** [comment]
微信tank123456wuhan求拉

**Comment by lijibing01** [comment]
微信wxid_yk6js1251shf21求拉

**Comment by liminglu** [comment]
微信 13675811558 求拉

**Comment by wujianglong** [comment]
微信 15170037957 求拉

**Comment by 25juan** [comment]
@xuqingkuang 帮忙加一下呢 微信企业截图看不到微信号：wx1216181067

**Comment by Anne-Tao** [comment]
微信号:wutao-wx求拉

**Comment by a523926245** [comment]
微信号:promise968164

**Comment by yumindeckard** [comment]
微信号 guiyumin002

谢谢

**Comment by cjanyl** [comment]
看不到图片啊。微信号cjanyl  求拉
谢谢

**Comment by PrinceWong424** [comment]
微信：wj1996424 前来报到

**Comment by zhaozheyu** [comment]
微信 ssskyce 求拉

**Comment by heda20** [comment]
微信 heda20 求拉

**Comment by zhiguoliang** [comment]
微信 sskk0608求拉

**Comment by fsxiaoke** [comment]
> @duanpengcheng520 @tt990218 @weizhanzhan @fulus06 @todayliu @97zhaodashuai @dbl520 建了个 2000 人的 QQ 大群，一起来加吧。

群号发下吧

微信号: daxiang0809
方便的话，拉一下

**Comment by lexguy** [comment]
不要再留微信号等拉了。按F12 ，选择图片元素，那个图片的地址就可以看到，然后复制出来自己打开，就可以可以加载出来了。直接贴出来吧，QQ 群号 **784894901**

**Comment by aminaka-ui** [comment]
你哪里拉米，滾回去吧！中國大陸浙江衛視網膜病變
