### ISSUE TITLE
refreshWrapper包裹的listView，如果里面有横向的scrollView，下拉刷新会和ScrollView 事件冲突

### ISSUE THREAD

**Issue by linpenghui958** [Tencent/Hippy#309]
**Describe the bug**
用refreshWrapper包裹的listView，如果里面有横向的scrollView，安卓机，下拉刷新会和横向的滑动同时触发

**Expected behavior**
期望ScrollView 事件优先，不透传到上层。

**Screenshots**

**Smartphone (please complete the following information):**

- Device: HUAWEI P30 pro
- OS and version: android 9
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version hippy/react 2.0.3

**Comment by siguangli** [comment]
最新的版本可以使用pullHeader和pullFooter组件，不推荐使用refreshWrapper
