### ISSUE TITLE
flex布局异常

### ISSUE THREAD

**Issue by LuChenyang3842** [Tencent/Hippy#315]
**Describe the bug**
flex布局异常，在justify-content:space-between时，若冗余空间小于1会导致布局异常

**To Reproduce**

``` html
<template>
  <div style="flex: 1">
    <div class="container">
      <div v-for="n in 3" :key="n" class="item"></div>
    </div>
  </div>
</template>

<style lang="scss" scoped>

.container {
  width: 373;
  height: 200;
  background-color: #3e3e3e;
  flex-direction: row;
  justify-content: space-between;
}

.item {
  width: 124;
  height: 199;
  background-color: #a14646;
}

</style>
```

**Expected behavior**
布局正常

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iphone8
- OS and version: iOS 13.3.1
- Front-end SDK and version: @hippy/vue 2.0.1

**Additional context**

**Comment by meloalright** [comment]
```diff
.item {
  width: 124;
  height: 199;
+  flex-shrink: 1;
  background-color: #a14646;
}
```

@LuChenyang3842 看起来你可以加上一行 `flex-shrink: 1` 来解决
主要原因是这里的 native 端 FlexShrink 默认是 0

**Comment by meloalright** [comment]
Reference the issue #672

**Comment by zoomchan-cxj** [comment]
这里确实有一些历史原因，这里默认值设置还是会保留0，我们会在文档里补充一下
