### ISSUE TITLE
A crash occurred JSCCtxValue JSValueUnprotect(context_,value_)

### ISSUE THREAD

**Issue by 0xBa0** [Tencent/Hippy#3384]
### Version

2.16.4

### Platform

iOS

### Architecture

arm

### Reproduce Condition

iPhone6，iOS12 系统，demo 启动就崩溃了，必现

### Additional Information

<img width="1702" alt="WeChatWorkScreenshot_bdc56d05-0a18-46bb-b185-6474a92222b4" src="https://github.com/Tencent/Hippy/assets/39689377/1cc1a4f6-6591-40bc-b486-e0ebaa2bd656">

**Comment by wtj900** [comment]
请问这个问题有修复吗？

**Comment by etkmao** [comment]
fixed. https://github.com/Tencent/Hippy/pull/3344
