### ISSUE TITLE
项目跟内部 CI 还有关系么？

### ISSUE THREAD

**Issue by kassadin** [Tencent/Hippy#34]
https://github.com/Tencent/Hippy/blob/a707d975364649e96b7743fc618fda7bbe1d016c/android/sdk/build.gradle#L4-L9

sdk 内已经有编译好的 jniLibs，是否可以先删除 `build.gradle` 中的 ci 及 ndk 相关编译配置，不依赖 ndk，简化 demo 运行条件。

ndk 依赖及配置已经太老了，需要迁移到新版本

**Comment by xuqingkuang** [comment]
讲道理工具链确实需要升级了。

这个有点像历史遗留问题，因为还能用所以一直没升级。
