### ISSUE TITLE
ViewPager多个子容器（非同一样式）渲染后，左右滑动，存在页面抖动

### ISSUE THREAD

**Issue by lansee** [Tencent/Hippy#340]
两个子容器示例：
![image](https://user-images.githubusercontent.com/7961271/92705991-bb31ed00-f386-11ea-80a1-a66068763814.png)
![image](https://user-images.githubusercontent.com/7961271/92706007-bff6a100-f386-11ea-8c59-3f53539496d0.png)

在渲染后，左右滑动存在高度不一致
![image](https://user-images.githubusercontent.com/7961271/92706098-d7ce2500-f386-11ea-8ed2-bd271c2ebcdd.png)
![image](https://user-images.githubusercontent.com/7961271/92706303-fcc29800-f386-11ea-9259-de69c4cb7d67.png)

两个子容器差别：热门tab 多一个 排行的view

**Comment by xuqingkuang** [comment]
其实没太看出来问题是什么，还请给出正确和错误两种范例。
