### ISSUE TITLE
rn-web  scrollView 的onscrollTo ， scrollEnabled 设置后不生效

### ISSUE THREAD

**Issue by tracyxu5298** [Tencent/Hippy#350]
rt 。 在hippy rn-web下 使用scrollView 插件，监听onscrollBeginDrag 没有触发，设置禁止滑动也没生效

**Comment by tracyxu5298** [comment]
横向滑动时

**Comment by zoomchan-cxj** [comment]
onscrollBeginDrag 不是标准web事件，暂时没有打算加到react-web里，scrollEnabled #494 已经支持
