### ISSUE TITLE
hippy目前实现自绘了吗?

### ISSUE THREAD

**Issue by luka26** [Tencent/Hippy#361]
我看有文章提到会采用自绘引擎,类似flutter,有没有对比的文章?

**Comment by liyujiang-gzu** [comment]
同样关心。有计划支持HarmonyOS吗？看到华为鸿蒙系统目前放出来的开发方案是HML+CSS+JS，都是JS方案，目测Hippy是容易支持鸿蒙系统的吧

**Comment by TheLittleBoy** [comment]
听说自绘引擎是3.0的目标

**Comment by zoomchan-cxj** [comment]
自绘目前在开发中，3.0会上，在某些方面甚至会比flutter更优
