### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by asterpang** [Tencent/Hippy#3719]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]iPhone13,2
- OS and version: [e.g. iOS 13.3.1]17.2.1 (21C66)
- Hippy native SDK version: [e.g. 2.0.0]2.15.7
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

#45

SIGSEGV

解析 原始
0
SIGSEGV:SEGV_ACCERR
1
0 CoreText 0x00000001a62feef8 0x00000001a62f8000 + 28408
2
1 CoreText 0x00000001a62fee78 0x00000001a62f8000 + 28280
3
2 CoreText 0x00000001a62fe908 0x00000001a62f8000 + 26888
4
3 CoreText 0x00000001a62fd870 0x00000001a62f8000 + 22640
5
4 CoreText 0x00000001a62fd5a0 0x00000001a62f8000 + 21920
6
5 CoreText 0x00000001a63a98c0 0x00000001a62f8000 + 727232
7
6 CoreText 0x00000001a639055c CTTypesetterCreateWithRunArrayAndOptions + 108
8
7 UIFoundation 0x00000001afca294c 0x00000001afc43000 + 391500
9
8 UIFoundation 0x00000001afca15f4 0x00000001afc43000 + 386548
10
9 UIFoundation 0x00000001afca3d40 0x00000001afc43000 + 396608
11
10 UIFoundation 0x00000001afca3280 0x00000001afc43000 + 393856
12
11 UIFoundation 0x00000001afca7220 0x00000001afc43000 + 410144
13
12 UIFoundation 0x00000001afd021b8 0x00000001afc43000 + 782776
14
13 UIFoundation 0x00000001afd030f0 0x00000001afc43000 + 786672
15
14 UIFoundation 0x00000001afca7bac 0x00000001afc43000 + 412588
16
15 UIFoundation 0x00000001afc8ed38 0x00000001afc43000 + 310584
17
16 UIFoundation 0x00000001afc904f4 0x00000001afc43000 + 316660
18
17 UIFoundation 0x00000001afc9dee8 0x00000001afc43000 + 372456
19
18 UIFoundation 0x00000001afcd76fc 0x00000001afc43000 + 607996
20
19 QQKSong 0x00000001005b5a68 HippyParseType + 46192
21
20 QQKSong 0x00000001005b4684 HippyParseType + 41100
22
21 QQKSong 0x00000001005fcff8 _ZN7MTTNode16layoutSingleNodeEf11MeasureModefS0_16FlexLayoutActionPv + 244
23
22 QQKSong 0x00000001005fcb20 _ZN7MTTNode23calculateItemsFlexBasisE7MTTSizePv + 376
24
23 QQKSong 0x00000001005fc280 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 816
25
24 QQKSong 0x00000001005fcb20 _ZN7MTTNode23calculateItemsFlexBasisE7MTTSizePv + 376
26
25 QQKSong 0x00000001005fc280 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 816
27
26 QQKSong 0x00000001005fcb20 _ZN7MTTNode23calculateItemsFlexBasisE7MTTSizePv + 376
28
27 QQKSong 0x00000001005fc280 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 816
29
28 QQKSong 0x00000001005fd328 _ZN7MTTNode22determineCrossAxisSizeERNSt3__16vectorIP8FlexLineNS0_9allocatorIS3_EEEE7MTTSize16FlexLayoutActionPv + 408
30
29 QQKSong 0x00000001005fc498 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 1352
31
30 QQKSong 0x00000001005fd328 _ZN7MTTNode22determineCrossAxisSizeERNSt3__16vectorIP8FlexLineNS0_9allocatorIS3_EEEE7MTTSize16FlexLayoutActionPv + 408
32
31 QQKSong 0x00000001005fc498 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 1352
33
32 QQKSong 0x00000001005fd328 _ZN7MTTNode22determineCrossAxisSizeERNSt3__16vectorIP8FlexLineNS0_9allocatorIS3_EEEE7MTTSize16FlexLayoutActionPv + 408
34
33 QQKSong 0x00000001005fc498 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 1352
35
34 QQKSong 0x00000001005fddd4 _ZN7MTTNode16layoutFixedItemsE11MTTSizeModePv + 392
36
35 QQKSong 0x00000001005fc520 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 1488
37
36 QQKSong 0x00000001005fd658 _ZN7MTTNode22determineCrossAxisSizeERNSt3__16vectorIP8FlexLineNS0_9allocatorIS3_EEEE7MTTSize16FlexLayoutActionPv + 1224
38
37 QQKSong 0x00000001005fc498 _ZN7MTTNode10layoutImplEff12MTTDirection16FlexLayoutActionPv + 1352
39
38 QQKSong 0x00000001005fbde8 _ZN7MTTNode6layoutEff12MTTDirectionPv + 260
40
39 QQKSong 0x00000001005ac008 HippyParseType + 6672
41
40 QQKSong 0x00000001005d2d1c HippyGetUIManagerQueue + 6584
42
41 QQKSong 0x00000001005d77c4 HippyGetUIManagerQueue + 25696
43
42 QQKSong 0x00000001005d5348 HippyGetUIManagerQueue + 16356
44
43 CoreFoundation 0x00000001a497b794 0x00000001a494a000 + 202644
45
44 CoreFoundation 0x00000001a497b22c 0x00000001a494a000 + 201260
46
45 CoreFoundation 0x00000001a497b054 0x00000001a494a000 + 200788
47
46 QQKSong 0x00000001005a2628 _Z25HippyParseMethodSignatureP8NSStringPU15__autoreleasingP7NSArrayIP19HippyMethodArgumentE + 12568
48
47 QQKSong 0x0000000100560ac4 MttHippyException + 60264

**Comment by wwwcg** [comment]
请提供正确翻译后的堆栈信息以帮助定位
