### ISSUE TITLE
iOS Hippy 2.17.2 HPOPAnimator Crash

### ISSUE THREAD

**Issue by wtj900** [Tencent/Hippy#3725]
**Describe the bug**
Swift和OC混编项目，Crash，比较高概率复现

- Device: iPhone 设备不定
- OS and version: 系统不定
- Hippy native SDK version: 2.17.2

**Additional context**

0 MyApp HPOP::Vector::data() + 12
1 MyApp _POPBasicAnimationState::advance(double, double, objc_object*) + 440
2 MyApp _POPAnimationState::advanceTime(double, objc_object*) + 276
3 MyApp applyAnimationTime(objc_object*, _POPAnimationState*, double) + 76
4 MyApp -[HPOPAnimator _renderTime:item:] + 476
5 MyApp __34-[HPOPAnimator _renderTime:items:]_block_invoke + 84
6 libdispatch.dylib __dispatch_call_block_and_release + 32
12libsystem_pthread.dylib __pthread_wqthread + 288

**Comment by wwwcg** [comment]
@wtj900 能否提供下相关的动画示例代码？方便我们复现下

**Comment by wwwcg** [comment]
Since there is no reply, we will close this issue for now.
If you have more specific information, please feel free to provide.
