### ISSUE TITLE
步骤太乱了

### ISSUE THREAD

**Issue by Tians9457** [Tencent/Hippy#3737]
这Android与ios的步骤集成是不是不给新人看啊！
草草了事

**Comment by mengjie0320** [comment]
如果搭建环境遇到问题可以看看这篇是否可以帮到你：[hippy 调试demo运行联调-mac环境准备篇](https://mp.csdn.net/mp_blog/creation/success/136390535)；其中mac的ios端模拟截至今日还待补充
