### ISSUE TITLE
hippy-vue-next-demo 启动web renderer问题

### ISSUE THREAD

**Issue by daijingfeng** [Tencent/Hippy#3780]
**Describe the bug**
在main分支下，driver/js/examples/hippy-vue-next-demo，执行npm run web:dev后，再打开3000端口，未能正常显示页面。报错信息如图。
<img width="703" alt="企业微信截图_330be947-ae45-41e8-acf5-c725291220f9" src="https://github.com/Tencent/Hippy/assets/17313078/bf625701-5ebd-412d-a950-a4401233d26b">

**To Reproduce**

1. cd driver/js/examples/hippy-vue-next-demo
2. npm i
3. npm run web:dev
4. 打开localhost:3000

**Expected behavior**
master分支下，examples/hippy-vue-next-demo，执行npm run web:dev，可以正常访问localhost:3000页面。
<img width="460" alt="企业微信20240318-140718@2x" src="https://github.com/Tencent/Hippy/assets/17313078/cdb14c21-baf8-43d6-995f-55bca8172ea2">

**Smartphone (please complete the following information):**

- Device: Mac M1
- Node version: 16.16.0

**Comment by tysong1** [comment]
楼主解决了吗？我也遇到了这个问题，并且master上的vue-next-demo点击等事件没法触发

**Comment by hpsoar** [comment]
master分支启动后不能点击的问题，我也遇到了，解决方案参考：https://github.com/Tencent/Hippy/issues/3176
```
example 的 hippy-react-demo 项目下，执行 web:dev 和 web:build 编译运行的时候，在 Chrome 浏览器打开页面点击组件不能触发 onClick 事件，但是 F12 进入开发者模式 => 选择移动端浏览器，点击的时候就能触发 onClick 事件；
同时，执行 serve 和 build 构建后的时候都可以触发 onClick
```

SceneBuilder报错的问题：目前3.x对web端支持还未适配。SceneBuilder在web端未实现。

**Comment by villiamVIX** [comment]
楼主解决了吗？我也遇到了这个问题
