### ISSUE TITLE
2.17.0版本和3.x版本pod之后logging文件报错，直接无法运行

### ISSUE THREAD

**Issue by faber0709** [Tencent/Hippy#3889]
2.17.0版本和3.x版本pod之后logging文件报错，直接无法运行
![截屏2024-06-11 15 06 11](https://github.com/Tencent/Hippy/assets/24383276/88c36bd8-672f-4680-9040-1c8bc6edd17d)
![截屏2024-06-11 15 06 39](https://github.com/Tencent/Hippy/assets/24383276/a6177373-a4fb-4807-9ff6-985d4982fb2c)

**Comment by wwwcg** [comment]
请确保集成合入如下PR的最新版本，如2.16.6、2.17.4等
https://github.com/Tencent/Hippy/pull/3767

**Comment by faber0709** [comment]
更新之后依旧无法运行，Xcode15.3。版本3.2.0-beta
![截屏2024-06-13 17 34 15](https://github.com/Tencent/Hippy/assets/24383276/011b6d0e-bc6b-4a54-a7ed-8ed7d1986d48)
