### ISSUE TITLE
  pod 'hippy', '3.0.0'重复文件错误

### ISSUE THREAD

**Issue by faber0709** [Tencent/Hippy#3890]
github上的demo代码，直接将本地依赖替换成远程依赖直接报重复文件错误。自己创建一个项目pod install 也是一样的问题
版本号3.0.0
![Uploading 截屏2024-06-11 16.02.09.png…]()

**Comment by wwwcg** [comment]
请使用2.x或3.2.x最新代码，3.3 Release版本即将发布。
3.0或3.1版本问题较多，不建议使用。
