### ISSUE TITLE
版本3.2.0-beta，pod install之后无法运行

### ISSUE THREAD

**Issue by faber0709** [Tencent/Hippy#3904]
版本3.2.0-beta，pod install之后无法运行
Xcode版本15.3
![截屏2024-06-13 17 37 04](https://github.com/Tencent/Hippy/assets/24383276/301ff2fc-0fc9-4556-a73d-1827757dbbee)

**Comment by faber0709** [comment]
分支是3.2.x

**Comment by loumzy** [comment]
@faber0709 
<img width="1206" alt="image" src="https://github.com/Tencent/Hippy/assets/8309821/6a82d2af-167c-4c93-9bca-66a74c1335cc">
https://github.com/sohotz/Hippy/blob/main/docs/development/native-integration.md

**Comment by faber0709** [comment]
直接pod 3.2.0，是找不到这个版本的










在 2024-06-17 18:33:18，"loumzy" ***@***.***> 写道：

@faber0709
image.png (view on web)
https://github.com/sohotz/Hippy/blob/main/docs/development/native-integration.md

**Comment by wwwcg** [comment]
已发布3.3.0 正式版，修复了部分podspec问题，历史beta版本不建议接入
