### ISSUE TITLE
vue-next中beforeLoadStyle方法 在3.3.X版本不生效，在2.17.x正常

### ISSUE THREAD

**Issue by villiamVIX** [Tencent/Hippy#3969]
```js
const app: HippyApp = createApp(App, {
  // hippy native module name
  appName: 'Demo',

 styleOptions: {
    beforeLoadStyle: (decl)=>{
      let { type, property, value } = decl;
 
        const regex = /\b(width|height|margin|padding|top|bottom|left|right|font-size|line-height)\b/;

        if(regex.test(property)){

          value = Number(value) * 1.5;

      return { ...decl, value};
    },
    // ratioBaseWidth: 720,
  },

});
```
同样的代码在hippy的3.3.X用vue2可以触发生效。但是在vue3中没有触发。

**Comment by dreamdesky** [comment]
+1

**Comment by villiamVIX** [comment]
> +1

所以你们怎么解决，我们先退回vue2了

**Comment by dreamdesky** [comment]
我们不着急，先等官方修 bug， @villiamVIX @zoomchan-cxj

**Comment by villiamVIX** [comment]
> 我们不着急，先等官方修 bug， @villiamVIX @zoomchan-cxj

好像 issue基本没做回复🥚

**Comment by villiamVIX** [comment]
```js
          <span style="max-width: 200px">{{ rect2 }}</span>
```

这种写法的会被beforeLoadStyle触发 ；  所有<style>里的css都不会被处罚

**Comment by villiamVIX** [comment]
@xuqingkuang @zoomchan-cxj 可否安排处理呢

**Comment by gguoyu** [comment]
> ```js
> const app: HippyApp = createApp(App, {
>   // hippy native module name
>   appName: 'Demo',
> 
>  styleOptions: {
>     beforeLoadStyle: (decl)=>{
>       let { type, property, value } = decl;
>  
>         const regex = /\b(width|height|margin|padding|top|bottom|left|right|font-size|line-height)\b/;
> 
>         if(regex.test(property)){
> 
>           value = Number(value) * 1.5;
> 
>       return { ...decl, value};
>     },
>     // ratioBaseWidth: 720,
>   },
> 
> });
> ```
> 
> 同样的代码在hippy的3.3.X用vue2可以触发生效。但是在vue3中没有触发。

有两个问题确认下。
1、请问这里用的hippy sdk 是什么版本的，是3.x的还是2.x？
2、这里说3.3.x不生效，在2.17.x正常，这里2.17.x指的是2.17.x的vue-next还是2.17.x的vue2呢？

**Comment by villiamVIX** [comment]
SDK3.3.X+vue2 ✔
SDK3.3.X+vue3 只有css in js里的会触发，写在<style>里的都不触发
SDK2.17.X+vue3 ✔ 

① 这里用的3.3.X的SDK+vue3异常
② 同样用的2.17.X的vue3 ； 配2.17的sdk正常；配3.3.x的sdk不触发
另外 今天试了用3.3.x的vue3+3.3.x的sdk，也是只有

**Comment by villiamVIX** [comment]
> SDK3.3.X+vue2 ✔ SDK3.3.X+vue3 只有css in js里的会触发，写在<style>里的都不触发 SDK2.17.X+vue3 ✔
> 
> ## ① 这里用的3.3.X的SDK+vue3异常
> ② 同样用的2.17.X的vue3 ； 配2.17的sdk正常；配3.3.x的sdk不触发
> 另外 今天试了用3.3.x的vue3+3.3.x的sdk（以demo-div.vue为例）也是只有css in js的样式会触发，<style>不触发

**Comment by villiamVIX** [comment]
@gguoyu 
- SDK3.3.X+vue2 ✔  
- SDK3.3.X+vue3 只有css in js里的会触发，写在<style>里的都不触发 
- SDK2.17.X+vue3 ✔

① 这里用的3.3.X的SDK+vue3异常
② 同样用的2.17.X的vue3 ； 配2.17的sdk正常；配3.3.x的sdk不触发
另外 今天试了用3.3.x的vue3+3.3.x的sdk（以demo-div.vue为例）也是只有css in js的样式会触发，<style>不触发

> > ```js
> > const app: HippyApp = createApp(App, {
> >   // hippy native module name
> >   appName: 'Demo',
> > 
> >  styleOptions: {
> >     beforeLoadStyle: (decl)=>{
> >       let { type, property, value } = decl;
> >  
> >         const regex = /\b(width|height|margin|padding|top|bottom|left|right|font-size|line-height)\b/;
> > 
> >         if(regex.test(property)){
> > 
> >           value = Number(value) * 1.5;
> > 
> >       return { ...decl, value};
> >     },
> >     // ratioBaseWidth: 720,
> >   },
> > 
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 同样的代码在hippy的3.3.X用vue2可以触发生效。但是在vue3中没有触发。
> 
> 有两个问题确认下。 1、请问这里用的hippy sdk 是什么版本的，是3.x的还是2.x？ 2、这里说3.3.x不生效，在2.17.x正常，这里2.17.x指的是2.17.x的vue-next还是2.17.x的vue2呢？

**Comment by villiamVIX** [comment]
> 好的，看起来应该是3.x 的sdk 下 vue-next 3.x 版本有问题。 我们验证下，感谢反馈问题

好的 ！ 感谢！   期待修复

**Comment by villiamVIX** [comment]
> 好的，看起来应该是3.x 的sdk 下 vue-next 3.x 版本有问题。 我们验证下，感谢反馈问题

3.x 的sdk 下 vue-next 的代码在 sdk2.17上运行也是正常的，会不会是sdk3.x的问题呢？

**Comment by villiamVIX** [comment]
> 好的，看起来应该是3.x 的sdk 下 vue-next 3.x 版本有问题。 我们验证下，感谢反馈问题
@gguoyu  打扰下
sdk3.x下的 vue3 运行在 sdk2.17上是能正常触发的，所以会不会是sdk3.x的问题呢？

**Comment by gguoyu** [comment]
问题原因我们已经找到了，近期会修复哈

**Comment by zealotchen0** [comment]
@villiamVIX @dreamdesky 
感谢大家反馈，我们已在修复了这个问题，参考 [commit](https://github.com/Tencent/Hippy/commit/ac3fd3dbce1498f5acee41d0e0bfe9ef1f3f7aa3)

**Comment by villiamVIX** [comment]
> @villiamVIX @dreamdesky 感谢大家反馈，我们已修复了这个问题，参考 [commit](https://github.com/Tencent/Hippy/commit/ac3fd3dbce1498f5acee41d0e0bfe9ef1f3f7aa3)

@gguoyu @zealotchen0 
HIPPY动画里比如： translateX/Y translate ， 有偏移量的动效 都没有经过beforeLoadStyle，这个能加进去吗？   不然一些偏移量都无法统一做处理

复现版本3.3.0sdk+vue2

```
const moveDuration = 1000;
const offset = 110 ;

const loopActions = {
  left: [
    {
      startValue: 0,
      toValue: offset,
      duration: moveDuration, // 动画持续时间
    },
    {
      startValue: offset,
      toValue: 0,
      duration: moveDuration, // 动画持续时间
      repeatCount: -1,
    }
  ],
  top: [
    {
      startValue: 0,
      toValue: offset,
      duration: moveDuration, // 动画持续时间
    },
    {
      startValue: offset,
      toValue: 0,
      duration: moveDuration, // 动画持续时间
      repeatCount: -1,
    },
  ]
};

```
