### ISSUE TITLE
3.3.x开启debug模式 新建的页面是白屏 报：load coreJsBundle failed, check your core jsBundle:run script error

### ISSUE THREAD

**Issue by villiamVIX** [Tencent/Hippy#3970]
![image](https://github.com/user-attachments/assets/9a05b118-e69d-4699-833f-39be6e3652cf)

![image](https://github.com/user-attachments/assets/ead3d796-6ace-48b7-8913-4181206b86df)

所有代码都是刚clone下来的 没改动

**Comment by heiha100** [comment]
> ![image](https://private-user-images.githubusercontent.com/58601148/352788673-9a05b118-e69d-4699-833f-39be6e3652cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2NzMtOWEwNWIxMTgtZTY5ZC00Njk5LTgzM2YtMzliZTZlMzY1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzNhN2U1OGI0YjllMzMxNTc2MjRkMzFmNGJlYWM4NWUzNDg4ZTk1OTMxMTJhNWI2NzU5YjM5MGUxOGU1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GgTI90lWfuV99RZMUkkXtqYLMVLa-B_9042MBe_yytQ)
> 
> ![image](https://private-user-images.githubusercontent.com/58601148/352788639-ead3d796-6ace-48b7-8913-4181206b86df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2MzktZWFkM2Q3OTYtNmFjZS00OGI3LTg5MTMtNDE4MTIwNmI4NmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWIzZDc1ZDEyMjBkMjJjZDY2MzcwMmQwY2I1NzExMTc1MDhhNzA3ODA4ZjY4Nzg0OWFiYzhiMGQ3MjFjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gVyytSYW8gfdgOXrtJhGMgKxjGmQwKFmVIbzRN0h97U)
> 
> 所有代码都是刚clone下来的 没改动

我也遇到了同样的问题，请问解决了吗

**Comment by villiamVIX** [comment]
> > ![image](https://private-user-images.githubusercontent.com/58601148/352788673-9a05b118-e69d-4699-833f-39be6e3652cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2NzMtOWEwNWIxMTgtZTY5ZC00Njk5LTgzM2YtMzliZTZlMzY1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzNhN2U1OGI0YjllMzMxNTc2MjRkMzFmNGJlYWM4NWUzNDg4ZTk1OTMxMTJhNWI2NzU5YjM5MGUxOGU1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GgTI90lWfuV99RZMUkkXtqYLMVLa-B_9042MBe_yytQ)
> > ![image](https://private-user-images.githubusercontent.com/58601148/352788639-ead3d796-6ace-48b7-8913-4181206b86df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2MzktZWFkM2Q3OTYtNmFjZS00OGI3LTg5MTMtNDE4MTIwNmI4NmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWIzZDc1ZDEyMjBkMjJjZDY2MzcwMmQwY2I1NzExMTc1MDhhNzA3ODA4ZjY4Nzg0OWFiYzhiMGQ3MjFjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gVyytSYW8gfdgOXrtJhGMgKxjGmQwKFmVIbzRN0h97U)
> > 所有代码都是刚clone下来的 没改动
> 
> 我也遇到了同样的问题，请问解决了吗

没解决

**Comment by heiha100** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/58601148/352788673-9a05b118-e69d-4699-833f-39be6e3652cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2NzMtOWEwNWIxMTgtZTY5ZC00Njk5LTgzM2YtMzliZTZlMzY1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzNhN2U1OGI0YjllMzMxNTc2MjRkMzFmNGJlYWM4NWUzNDg4ZTk1OTMxMTJhNWI2NzU5YjM5MGUxOGU1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GgTI90lWfuV99RZMUkkXtqYLMVLa-B_9042MBe_yytQ)
> > > ![image](https://private-user-images.githubusercontent.com/58601148/352788639-ead3d796-6ace-48b7-8913-4181206b86df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2MzktZWFkM2Q3OTYtNmFjZS00OGI3LTg5MTMtNDE4MTIwNmI4NmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWIzZDc1ZDEyMjBkMjJjZDY2MzcwMmQwY2I1NzExMTc1MDhhNzA3ODA4ZjY4Nzg0OWFiYzhiMGQ3MjFjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gVyytSYW8gfdgOXrtJhGMgKxjGmQwKFmVIbzRN0h97U)
> > > 所有代码都是刚clone下来的 没改动
> > 
> > 
> > 我也遇到了同样的问题，请问解决了吗
> 
> 没解决

知道怎么回事了，debug模式下并运行手机上选择的js demo, 而是运行`npm run hippy:dev`跑的项目。并且必须严格按照图中步骤执行(第7步不需要)
![image](https://github.com/user-attachments/assets/423e456f-4504-4f18-8163-c6727d250639)

**Comment by villiamVIX** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/58601148/352788673-9a05b118-e69d-4699-833f-39be6e3652cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2NzMtOWEwNWIxMTgtZTY5ZC00Njk5LTgzM2YtMzliZTZlMzY1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NzNhN2U1OGI0YjllMzMxNTc2MjRkMzFmNGJlYWM4NWUzNDg4ZTk1OTMxMTJhNWI2NzU5YjM5MGUxOGU1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GgTI90lWfuV99RZMUkkXtqYLMVLa-B_9042MBe_yytQ)
> > > > ![image](https://private-user-images.githubusercontent.com/58601148/352788639-ead3d796-6ace-48b7-8913-4181206b86df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzOTQzMDEsIm5iZiI6MTczNjM5NDAwMSwicGF0aCI6Ii81ODYwMTE0OC8zNTI3ODg2MzktZWFkM2Q3OTYtNmFjZS00OGI3LTg5MTMtNDE4MTIwNmI4NmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDAzNDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZWIzZDc1ZDEyMjBkMjJjZDY2MzcwMmQwY2I1NzExMTc1MDhhNzA3ODA4ZjY4Nzg0OWFiYzhiMGQ3MjFjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gVyytSYW8gfdgOXrtJhGMgKxjGmQwKFmVIbzRN0h97U)
> > > > 所有代码都是刚clone下来的 没改动
> > > 
> > > 
> > > 我也遇到了同样的问题，请问解决了吗
> > 
> > 
> > 没解决
> 
> 知道怎么回事了，debug模式下并不运行手机上选择的js demo, 而是运行`npm run hippy:dev`跑的项目。并且必须严格按照图中步骤执行(第7步不需要) ![image](https://private-user-images.githubusercontent.com/134051067/401440576-423e456f-4504-4f18-8163-c6727d250639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MDk0MTksIm5iZiI6MTczNjQwOTExOSwicGF0aCI6Ii8xMzQwNTEwNjcvNDAxNDQwNTc2LTQyM2U0NTZmLTQ1MDQtNGYxOC04MTYzLWM2NzI3ZDI1MDYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQwNzUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGUxODQyNTA1ZWYzYmVhMGVmMGQxZTY0NTBhNTI0YjgwMjkzYjk4NDgwOWZkMzBkYzQ0NGZlZmU5MTFmM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JSeNluRUhjqOvAERfcgUm_11Ue3pHkZ0Ve5k7nhjXLo)

感恩  学到了   后来直接接入现成项目，很少用这个官方demo  就没注意
