### ISSUE TITLE
Add copyright notices to code copied from react-native-web

### ISSUE THREAD

**Issue by necolas** [Tencent/Hippy#40]
This repository contains (modified) copies of source code taken from other open source projects, with the copyright notices removed against the terms of the license. [react-native-web](https://github.com/necolas/react-native-web/) is [MIT licensed](https://github.com/necolas/react-native-web/blob/0.11.7/LICENSE), which requires that the copyright notice be retained in the relevant files

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

* apply-layout: [hippy](https://github.com/Tencent/Hippy/blob/cd46465/packages/hippy-react-web/src/adapters/apply-layout.ts) : [react-native-web](https://github.com/necolas/react-native-web/blob/0.11.7/packages/react-native-web/src/modules/applyLayout/index.js)
* image-loader: [hippy](https://github.com/Tencent/Hippy/blob/cd46465/packages/hippy-react-web/src/adapters/image-loader.ts) : [react-native-web](https://github.com/necolas/react-native-web/blob/0.11.7/packages/react-native-web/src/modules/ImageLoader/index.js)
* unitless-numbers: [hippy](https://github.com/Tencent/Hippy/blob/cd46465/packages/hippy-react-web/src/adapters/unitless-numbers.ts), [react-native-web](https://github.com/necolas/react-native-web/blob/0.11.7/packages/react-native-web/src/modules/unitlessNumbers/index.js)

**Comment by xuqingkuang** [comment]
Sorry, we will audit our codes more carefully.

I will add the license belongs to you in both of the file headers and our License.

https://github.com/Tencent/Hippy/blob/master/LICENSE#L205

**Comment by xuqingkuang** [comment]
Hi, I had added the license to related codes you provided, could you take a look a the comments[1] ok?

And I found more codes are modified based on hippy-react-web, I'm 
 comparing the codes.

[1] https://github.com/xuqingkuang/Hippy/commit/3ecbdae2f97466be4e2fdb5541865587486f0dd1

**Comment by necolas** [comment]
Thanks!

**Comment by xuqingkuang** [comment]
Hi, @necolas commit is updated, please leave a review message.

https://github.com/xuqingkuang/Hippy/commit/1236e9d10d459d94f9f634ac5bee5a0d1eca4e85

**Comment by necolas** [comment]
Fixed by https://github.com/Tencent/Hippy/pull/60
