### ISSUE TITLE
3.3.0版本崩溃

### ISSUE THREAD

**Issue by wtj900** [Tencent/Hippy#4001]
平台：iOS
Hippy版本：3.3.0

崩溃堆栈如下：
Crashed: Hippy Dom 0x367484480 Thread
0  JavaScriptCore                 0x153dd48 pas_bootstrap_free_heap_allocate_with_alignment + 364
1  JavaScriptCore                 0x153dcb4 pas_bootstrap_free_heap_allocate_with_alignment + 216
2  JavaScriptCore                 0x154ce1c pas_large_expendable_memory_allocate + 100
3  JavaScriptCore                 0x155da00 ensure_size_lookup + 184
4  JavaScriptCore                 0x155e320 pas_segregated_heap_ensure_size_directory_for_size + 2236
5  JavaScriptCore                 0x152e4e4 bmalloc_heap_config_specialized_try_allocate_common_impl_slow + 436
6  JavaScriptCore                 0x151fc94 bmalloc_allocate_auxiliary_impl_impl_slow + 48
7  JavaScriptCore                 0x151f488 bmalloc_allocate_auxiliary_impl_casual_case + 424
8  JavaScriptCore                 0x1183fd0 JSC::constructWeakMap(JSC::JSGlobalObject*, JSC::CallFrame*) + 196
9  JavaScriptCore                 0x15a3af4 pas_reallocation_did_fail + 182124
10 JavaScriptCore                 0x15a0830 pas_reallocation_did_fail + 169128
11 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
12 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
13 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
14 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
15 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
16 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
17 JavaScriptCore                 0x15a15a8 pas_reallocation_did_fail + 172576
18 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
19 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
20 JavaScriptCore                 0x15a15a8 pas_reallocation_did_fail + 172576
21 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
22 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
23 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
24 JavaScriptCore                 0x15a15a8 pas_reallocation_did_fail + 172576
25 JavaScriptCore                 0x15a03c0 pas_reallocation_did_fail + 167992
26 JavaScriptCore                 0x15771d4 pas_reallocation_did_fail + 7486845396
27 JavaScriptCore                 0xc6a9e8 JSC::Interpreter::executeProgram(JSC::SourceCode const&, JSC::JSGlobalObject*, JSC::JSObject*) + 1012
28 JavaScriptCore                 0xe7f954 JSC::evaluate(JSC::JSGlobalObject*, JSC::SourceCode const&, JSC::JSValue, WTF::NakedPtr<JSC::Exception>&) + 236
29 JavaScriptCore                 0x4af92c JSEvaluateScriptInternal + 60
30 JavaScriptCore                 0x4afa80 JSEvaluateScript + 272
31 APP                  0x437cbec hippy::driver::napi::JSCCtx::RunScript(footstone::stringview::string_view const&, footstone::stringview::string_view const&) + 1138 (jsc_ctx.cc:1138)
32 APP                  0x430aa18 __65-[HippyJSExecutor executeApplicationScript:sourceURL:onComplete:]_block_invoke + 857 (shared_ptr.h:857)
33 APP                  0x430b2a8 -[HippyJSExecutor executeBlockOnJavaScriptQueue:] + 744 (shared_ptr.h:744)
34 CoreFoundation                 0x24b14 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
35 CoreFoundation                 0xc3f9c -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 268
36 APP                  0x430e348 std::__1::__packaged_task_func<std::__1::__bind<-[HippyJSExecutor setup]::$_0>, std::__1::allocator<std::__1::__bind<-[HippyJSExecutor setup]::$_0>>, void ()>::operator()() + 634 (shared_ptr.h:634)
37 APP                  0x430f5b4 std::__1::packaged_task<void ()>::operator()() + 2083 (future:2083)
38 APP                  0x443a60c footstone::runner::Worker::RunTask() + 114 (worker.cc:114)
39 APP                  0x443b5f0 std::__1::__function::__func<footstone::runner::Worker::Start(bool)::$_1, std::__1::allocator<footstone::runner::Worker::Start(bool)::$_1>, void ()>::operator()() + 125 (worker.cc:125)
40 APP                  0x4381860 footstone::runner::OnTimerCb(__CFRunLoopTimer*, footstone::runner::LooperDriver*) + 37 (looper_driver.cc:37)
41 CoreFoundation                 0xb7a2c __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
42 CoreFoundation                 0xb76d0 __CFRunLoopDoTimer + 1004
43 CoreFoundation                 0xb722c __CFRunLoopDoTimers + 288
44 CoreFoundation                 0x53888 __CFRunLoopRun + 1856
45 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific + 608
46 APP                  0x43819d4 footstone::runner::LooperDriver::Start() + 73 (looper_driver.cc:73)
47 APP                  0x443b6a0 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, footstone::runner::Worker::Start(bool)::$_2>>(void*) + 301 (thread:301)
48 libsystem_pthread.dylib        0x606c _pthread_start + 136
49 libsystem_pthread.dylib        0x10d8 thread_start + 8

**Comment by wwwcg** [comment]
从堆栈看为JS引擎无法分配内存导致的错误，可检查app虚拟内存使用是否存在异常
hippy层面暂时无法提供更多帮助
