### ISSUE TITLE
3.3.* 偶现Bundle加载崩溃

### ISSUE THREAD

**Issue by Star-Chao** [Tencent/Hippy#4034]
Crashed: com.hippy.bridge
0  libobjc.A.dylib                0x275c objc_release + 16
1  libobjc.A.dylib                0x275c objc_release_x0 + 16
2  APP                  0x3f7d308 HippyFileHandler::AbsoluteURLFromHippyFileURL(NSURL*, NSURL*) + 71 (HippyFileHandler.mm:71)
3  APP                  0x3f7d45c HippyFileHandler::RequestUntrustedContent(NSURLRequest*, NSDictionary*, NSOperationQueue*, void (unsigned long, unsigned long) block_pointer, void (NSData*, NSDictionary*, NSURLResponse*, NSError*) block_pointer, std::__1::shared_ptr<VFSUriHandler> () block_pointer) + 93 (HippyFileHandler.mm:93)
4  APP                  0x4087248 VFSUriLoader::RequestUntrustedContent(NSURLRequest*, NSDictionary*, NSOperationQueue*, void (unsigned long, unsigned long) block_pointer, void (NSData*, NSDictionary*, NSURLResponse*, NSError*) block_pointer) + 144 (VFSUriLoader.mm:144)
5  APP                  0x3f694c4 -[HippyBridge(VFSLoader) loadContentsAsynchronouslyFromUrl:method:params:body:queue:progress:completionHandler:] + 58 (HippyBridge+VFSLoader.mm:58)
6  APP                  0x3f6a44c -[HippyBundleLoadOperation main] + 96 (HippyBundleLoadOperation.mm:96)
7  APP                  0x3f6ad28 -[HippyBundleOperationQueue addOperations:] + 49 (HippyBundleOperationQueue.m:49)
8  APP                  0x3f60ee4 -[HippyBridge beginLoadingBundle:bundleType:completion:] + 603 (HippyBridge.mm:603)
9  APP                  0x3f60b60 __51-[HippyBridge loadBundleURL:bundleType:completion:]_block_invoke + 511 (HippyBridge.mm:511)
10 libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
12 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
13 libdispatch.dylib              0xbf30 _dispatch_lane_invoke + 380
14 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
15 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
16 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
17 libsystem_pthread.dylib        0x10cc start_wqthread + 8

**Comment by wwwcg** [comment]
resolved in 3.3.2 release
