### ISSUE TITLE
3.3.* HippyBundleLoadOperation 偶现操作崩溃

### ISSUE THREAD

**Issue by Star-Chao** [Tencent/Hippy#4035]
Crashed: com.hippy.bundleQueue (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x2d20 objc_release + 16
1  Foundation                     0x184ac NSKeyValueWillChangeWithPerThreadPendingNotifications + 500
2  APP                  0x3f6a710 -[HippyBundleLoadOperation setExecuting:] + 125 (HippyBundleLoadOperation.mm:125)
3  APP                  0x3f6a580 __32-[HippyBundleLoadOperation main]_block_invoke + 95 (HippyBundleLoadOperation.mm:95)
4  APP                  0x4087a68 invocation function for block in VFSUriLoader::RequestUntrustedContent(NSURLRequest*, NSDictionary*, NSOperationQueue*, void (unsigned long, unsigned long) block_pointer, void (NSData*, NSDictionary*, NSURLResponse*, NSError*) block_pointer) + 744 (shared_ptr.h:744)
5  APP                  0x3f7d844 invocation function for block in HippyFileHandler::RequestUntrustedContent(NSURLRequest*, NSDictionary*, NSOperationQueue*, void (unsigned long, unsigned long) block_pointer, void (NSData*, NSDictionary*, NSURLResponse*, NSError*) block_pointer, std::__1::shared_ptr<VFSUriHandler> () block_pointer) + 103 (HippyFileHandler.mm:103)
6  Foundation                     0x4e3dc __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
7  Foundation                     0x5fa90 -[NSBlockOperation main] + 100
8  Foundation                     0x39acc __NSOPERATION_IS_INVOKING_MAIN__ + 20
9  Foundation                     0x4a00c -[NSOperation start] + 764
10 Foundation                     0x4d4d8 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 20
11 Foundation                     0x5acec __NSOQSchedule_f + 180
12 libdispatch.dylib              0x46048 _dispatch_block_async_invoke2 + 104
13 libdispatch.dylib              0x64094 _dispatch_client_callout + 16
14 libdispatch.dylib              0x3bab8 _dispatch_continuation_pop$VARIANT$armv81 + 432
15 libdispatch.dylib              0x3b1f4 _dispatch_async_redirect_invoke + 580
16 libdispatch.dylib              0x48630 _dispatch_root_queue_drain + 328
17 libdispatch.dylib              0x48dec _dispatch_worker_thread2 + 160
18 libsystem_pthread.dylib        0x1dd4 _pthread_wqthread + 224
19 libsystem_pthread.dylib        0x193c start_wqthread + 8

**Comment by wwwcg** [comment]
#4028 fixed, use version 3.3.2-rc.1 and later

**Comment by wtj900** [comment]
3.3.2正式版本有计划什么时候发布吗？
