### ISSUE TITLE
请问一下鸿蒙支持的情况进展如何了?

### ISSUE THREAD

**Issue by zeku2022** [Tencent/Hippy#4120]
如题~~感谢

**Comment by erpapa** [comment]
有一个独立的分支：[https://github.com/sohotz/Hippy/tree/main/framework/examples](https://github.com/sohotz/Hippy/tree/main/framework/examples)

**Comment by zeku2022** [comment]
> 有一个独立的分支：https://github.com/sohotz/Hippy/tree/main/framework/examples

好的 谢谢
