### ISSUE TITLE
建议构建时导出类型文件，加个typing的配置

### ISSUE THREAD

**Issue by vastwu** [Tencent/Hippy#421]
最近在typescript项目里用 @hippy/react 时发现没有类型，本来想补一个，但是一看源码都是ts写的，只是没有产出，有点浪费呀，

建议内部产出个.d.ts，要么单独发个@types包

**Comment by aquariuslt** [comment]
+1

是否可以对 rollup 的构建配置进行更新，使用 rollup 官方的  `@rollup/plugin-typescript` 插件，加上 `tsconfig.json#compilerOptions`  同时生成定义文件。

see https://github.com/rollup/plugins/tree/master/packages/typescript#options
