### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Tencent/Hippy#43]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Engine](https://github.com/Tencent/Hippy/blob/cd46465a1c7f3df6768e8593e4e456b280000a65/core/engine.cc#L49 "Destructor for Engine")
- [napi_vm_release](https://github.com/Tencent/Hippy/blob/cd46465a1c7f3df6768e8593e4e456b280000a65/core/napi/jsc/js-native-api-jsc.cc#L183 "napi_vm_release function")
- [PlatformDestroy](https://github.com/Tencent/Hippy/blob/cd46465a1c7f3df6768e8593e4e456b280000a65/core/napi/v8/js-native-api-v8.h#L80 "PlatformDestroy function")

**Comment by churchill-zhang** [comment]
thanks for your suggestion

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Tencent/Hippy/commit/ba29be528af5f5ce279d2ad68675ce0424512761 "Deletion of three unnecessary checks").

[Were any update candidates left over](https://github.com/Tencent/Hippy/blob/ba29be528af5f5ce279d2ad68675ce0424512761/core/napi/v8/js-native-api-v8.h#L70 "Update candidate: Destructor for napi_vm__")?
