### ISSUE TITLE
2.0.x版本到2.1.x版本居然引入破坏性改动，有没有搞错啊？？？

### ISSUE THREAD

**Issue by lxjwlt** [Tencent/Hippy#432]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1782819/100848790-91d3b980-34bc-11eb-96bd-1a800dd784e4.png)

renderRow行为不一致，原来是返回数据项的，现在只返回索引了，有没有王法，版本规范呢？

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

**Comment by xuqingkuang** [comment]
看了一下是 hippy-react-web 的代码，https://github.com/Tencent/Hippy/commit/1fb9eefdaf5a8fbe4ab6aea0f857b37b020641a4

下个版本修复吧。

**Comment by zoomchan-cxj** [comment]
@lxjwlt 如果是按照examples例子和文档提供的能力，datasource是不会赋值的，所以都是undefined，即renderRow的实参都是index
