### ISSUE TITLE
hippy:vendor

### ISSUE THREAD

**Issue by yjiqje** [Tencent/Hippy#45]
1/3 Start to install hippy-dainan-demo dependencies
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 5.623s
2/3 Start to build project hippy-dainan-demo
npm ERR! missing script: hippy:vendor

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fscut\AppData\Roaming\npm-cache\_logs\2019-12-27T02_43_43_230Z-debug.log
npm ERR! missing script: hippy:build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fscut\AppData\Roaming\npm-cache\_logs\2019-12-27T02_43_43_942Z-debug.log
3/3 Copy the built files to native
cp: cannot stat './dist/ios/*': No such file or directory
cp: cannot stat './dist/android/*': No such file or directory
~/Desktop/alicms/Hippy
👌 All done, you can open your native app now, enjoy.

**Comment by xuqingkuang** [comment]
For windows developers, we recommended to use [ConEmu with Git shell](https://conemu.github.io/) to run the build script.

It's [notice in README](https://github.com/Tencent/Hippy#start-the-android-app-with-hippy-react-or-hippy-vue-demo).
