### ISSUE TITLE
Not friendly to Windows users[对windows用户不友好]

### ISSUE THREAD

**Issue by zzyyzz1992** [Tencent/Hippy#48]
package.json:
  "buildexample": "sh ./scripts/build-example.sh",

对windows用户不友好。
希望能在powershell下执行，毕竟wsl也不是特别方便

**Comment by xuqingkuang** [comment]
我这儿用 Mac 开发的，要不你提交一个 Powershell 或者 cmd 版本？

**Comment by fangyulovechina** [comment]
换台mac

**Comment by zzyyzz1992** [comment]
> 我这儿用 Mac 开发的，要不你提交一个 Powershell 或者 cmd 版本？
> 
> 其实我推荐用 ConEmu + Git bash 运行，Windows 上也挺好的。

朋友，鄙人能力有限，我觉得 #53 提议挺好的。
提这个issue是因为看到是tencent 大厂出品，希望能有好的开发体验。如果要做成熟的开源，则不因局限于单一平台，windows平台肯定是需要支持的，soon or later。


> 换台mac

@fangyulovechina 我有mac :)
