### ISSUE TITLE
Demo中第一个 div组件就有问题？

### ISSUE THREAD

**Issue by effortcheep** [Tencent/Hippy#54]
Demo中第一个 div组件就有问题？

同方向嵌套滚动视图是不是没适配？

web可以正常滚动，iOS中最外层div无法滚动导致底部E展示不出来，Android 没测试。

**Comment by xuqingkuang** [comment]
恭喜你碰到 Hippy 中的限制之一了，Hippy 如果要让视图可以滚动，只有两种办法，一种是 ul 映射到可回收垂直列表 ListView，一种是 div + 样式 overflow-x/y 映射到 ScrollView 可滚动组件。

浏览器之所以能滚是因为内容超出了窗口尺寸，但是 Hippy 下要滚动需要把一个可滚动组件做成容器才可以。

那块儿样式确实有问题，回头我看看吧。

**Comment by xuqingkuang** [comment]
Fixed in #71
