### ISSUE TITLE
hippy-vue-demo的babel配置建议

### ISSUE THREAD

**Issue by jinming6568** [Tencent/Hippy#568]
hippy-vue-demo的默认babel配置存在兼容问题，项目中使用的是@vue/cli-plugin-babel，如果未将main-native.js文件写入在babel.config.js的entryFiles中，会导致hippy项目缺失es.promise.finally的兼容代码，h5项目由于使用vue-cli-service，会将入口文件默认写入entryFiles，hippy项目自定义了webpack配置，所以并不会默认写入，需要手动写入，建议在README中标注下。
```
// babel.config.js
const path = require('path')
module.exports = {
  presets: [
    ['@vue/cli-plugin-babel/preset', {
      entryFiles: [
        path.resolve(__dirname, './src/main-native.js'),
      ],
    }],
  ],
};
```

**Comment by zoomchan-cxj** [comment]
这个配置已经删除了

**Comment by jinming6568** [comment]
> 这个配置已经删除了

就是因为删除了才有问题，可以试试用现在的hippy-vue-demo，在main-native.js写一个new Promise().finally()然后打包，代码里不会对其做任何兼容，ios11.2以下的机器都会报错。
