### ISSUE TITLE
Add linux support (not shown in readme)

### ISSUE THREAD

**Issue by tomyo** [Tencent/Hippy#58]

**Comment by xuqingkuang** [comment]
Sorry, we haven't tested the build process in Linux so far.

But most operations should be the same as macOS.

I'm looking for someone who will contribute more description of the build on Linux.

**Comment by tomyo** [comment]
Hi, the build process went well on linux, following the MacOS instruction.
Sadly, I'm not a Android Studio user, so I couln't do step 6:
