### ISSUE TITLE
SDK 和 NDK具体是什么版本了？

### ISSUE THREAD

**Issue by lijibing01** [Tencent/Hippy#64]
想跑一下demo但是跑起来就报错, 以前没用过android studio

**Comment by jeromehan** [comment]
> 想跑一下demo但是跑起来就报错, 以前没用过android studio

https://github.com/Tencent/Hippy/issues/39

**Comment by lijibing01** [comment]
@jeromehan 大佬这个是啥问题啊，版本太高了吗，我一点那个upgrade plugin发现会把代码也改了，导致还是跑不起来，我应该怎么做

**Comment by lijibing01** [comment]
![image](https://user-images.githubusercontent.com/26105855/71579760-feba3300-2b38-11ea-974d-79617194ee3d.png)

**Comment by jeromehan** [comment]
> @jeromehan 大佬这个是啥问题啊，版本太高了吗，我一点那个upgrade plugin发现会把代码也改了，导致还是跑不起来，我应该怎么做

不要upgrade plugin

**Comment by jeromehan** [comment]
![image](https://user-images.githubusercontent.com/19773879/71579942-a0418480-2b39-11ea-9a81-a7162cae7d28.png)

**Comment by lijibing01** [comment]
这个命令在windows是可以运行的吗

**Comment by lijibing01** [comment]
![image](https://user-images.githubusercontent.com/26105855/71580240-c3b8ff00-2b3a-11ea-9c59-e4bb422fcbd8.png)

**Comment by jeromehan** [comment]
> 这个命令在windows是可以运行的吗

就是windows快捷方式的意思，名字命名成mips64el-linux-android

**Comment by lijibing01** [comment]
![image](https://user-images.githubusercontent.com/26105855/71580520-00392a80-2b3c-11ea-8d3c-2b10bb13be85.png)

**Comment by jeromehan** [comment]
源码说明
编译要求： android Studio 2.2以上版本
NDK r14b以上
配置自己sdk里面的cmake到环境变量

如window下cmake的路径：D:\sdk\cmake\3.6.4111459\bin
编译步骤：
1:把项目导入Android studio

2: 选择sdk工程的assembleRelease进行编译

常见问题：如果发现上面的步骤都ok了但是还是编译不过可以尝试重启一下电脑，或者注销一下，这样是为了保证环境变量生效。

如果一直报编译不过可以展示屏蔽掉sdk目录下面的build.gradle这个函数
buildNdkLibs(dependsOn: (ISCI.toBoolean() ? dealNdkLibSymbols : stripSO), type: Copy)
改为  buildNdkLibs( type: Copy) 这样只是不去编译c++代码

windows需要配置cmake环境变量、现在是找不到cmake的位置报错的。如果真配置不好环境变量就把编译c++代码干掉吧

**Comment by lijibing01** [comment]
感谢大佬，重启电脑没有解决。注释代码解决的。晚点研究一下cmake。还想问个问题，如果想用这个框架开发APP的话怎么调原生的功能啊，比如支付，打开别的app，消息推送

**Comment by jeromehan** [comment]
> 感谢大佬，重启电脑没有解决。注释代码解决的。晚点研究一下cmake。还想问个问题，如果想用这个框架开发APP的话怎么调原生的功能啊，比如支付，打开别的app，消息推送

本来hippy就是fork rn代码，在它的基础上修改的。会rn基本上没什么问题了

**Comment by lijibing01** [comment]
好的，谢谢大佬

**Comment by aluo44** [comment]
执行In -sf aarch64-linux-android-4.9 mips64el-linux-android的时候报错了

**Comment by aluo44** [comment]
执行In -sf aarch64-linux-android-4.9 mips64el-linux-android的时候报错了

C:\Users\apple\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains>In -sf aarc
h64-linux-android-4.9
'In' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by lijibing01** [comment]
@aluo44 是ln 不是in

**Comment by aluo44** [comment]
@lijibing01 C:\Users\apple\AppData\Local\Android\Sdk\ndk\20.1.5948944\toolchains>ln -sf aarc
h64-linux-android-4.9 mips64el-linux-android
'ln' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
这个也是一样

**Comment by lijibing01** [comment]
用git bash不要用cmd试试
![image](https://user-images.githubusercontent.com/26105855/71614689-303e0780-2be8-11ea-877c-f569f83be165.png)

**Comment by aluo44** [comment]
好了  谢谢

**Comment by aluo44** [comment]
刚才那个好了  又出现新问题了
![微信截图_20191231161735](https://user-images.githubusercontent.com/40012637/71614858-19e47b80-2be9-11ea-8d80-0ae710ec654e.png)

**Comment by lijibing01** [comment]
看下是不是ndk没有配置
![image](https://user-images.githubusercontent.com/26105855/71614937-79db2200-2be9-11ea-8796-e5431530c1b4.png)

**Comment by aluo44** [comment]
配好了  环境也检查过了  确定没有问题
![微信截图_20191231162602](https://user-images.githubusercontent.com/40012637/71615069-4220aa00-2bea-11ea-8bc0-1117ba9608cb.png)

**Comment by lijibing01** [comment]
那就不清楚啦，可能你需要那位大佬的帮助

**Comment by Mrlilili** [comment]
![image](https://user-images.githubusercontent.com/8361655/72333337-95b8ea80-36f6-11ea-9764-43b6d6550e25.png)

这个异常是什么原因？

**Comment by churchill-zhang** [comment]
cmake版本对吗
