### ISSUE TITLE
Vue版本编译失败

### ISSUE THREAD

**Issue by CarryHekangkai** [Tencent/Hippy#654]
1.npm install、npm run build、npm run buildexample hippy-react-demo分别是在哪个目录下运行？

2.lerna bootstrap，'lerna' 不是内部或外部命令，也不是可运行的程序或批处理文件。要怎么办？

3.编译Vue版本，运行npm run build报错，hippy-vue-demo@2.0.0 build: `vue-cli-service build`
![image](https://user-images.githubusercontent.com/35455762/112569328-f2e21d00-8e1e-11eb-883b-e7ddc35c13c1.png)

**Comment by zoomchan-cxj** [comment]
1. readme都有说明是根目录（Root directory）
2. lerna如果在根目录npm install自动会安装，如果没有运行npn install lerna -g
3. demo直接进入项目目录后，调试模式运行npm run hippy:dev -> npm run hippy:debug,  非调试模式npm run hippy:vendor再执行npm run build
