### ISSUE TITLE
安卓如何才能实现访问部署在服务器的js页面？

### ISSUE THREAD

**Issue by CarryHekangkai** [Tencent/Hippy#655]
安卓如何才能实现访问部署在服务器的js页面？能否在Demo里面也体现以下或者补充文档说明。

**Comment by zoomchan-cxj** [comment]
调试模式就是，可以看我们官网介绍[官网介绍](https://hippyjs.org/#/guide/debug)

**Comment by CarryHekangkai** [comment]
谢谢
