### ISSUE TITLE
访问远程界面如何配置？

### ISSUE THREAD

**Issue by CarryHekangkai** [Tencent/Hippy#657]
![image](https://user-images.githubusercontent.com/35455762/112798971-4fa03a80-90a0-11eb-8e35-8dfd6d5319d7.png)
![image](https://user-images.githubusercontent.com/35455762/112799037-647cce00-90a0-11eb-821b-5ef8969e17f6.png)
实在是搞不明白怎么在正式模式下进行设置远程服务器IP，只看到一个debugServerHost是DEBUG模式下用到的

**Comment by CarryHekangkai** [comment]
hippy-react-demo编译出index.android.js和vendor.android.js，把index.android.js和vendor.android.js复制到android-demo中后，hippy-react-demo是否已经对项目正常运行没有作用了？仅index.android.js和vendor.android.js就可以支持项目正常运行？

**Comment by CarryHekangkai** [comment]
编译后同时产生的1.android.js和vendor-manifest.json文件有什么作用？

**Comment by CarryHekangkai** [comment]
index.android.js和vendor.android.js有什么作用？存在怎样的对应关系？index.android.js和vendor.android.js是必须以资源文件的形式打包在app内部而不能动态load吗？动态load index.android.js和vendor.android.js然后加载，这种方案是否可行？

**Comment by CarryHekangkai** [comment]
原生Activity页面和前端hippy-react或者hippy-vue互相间跳转，目前只能想到前端可以通过Natvite提供的@HippyMethod方法startActivity的方式进行跳转页面，是否还有其他更优雅的方式实现？原生XActivity -> index.android.js -> YActivity -> index.android.js 这样子的页面切换路径如何实现？

**Comment by CarryHekangkai** [comment]
以上都是不太懂React/Vue的 Android 开发小白在看了几天文档后搞不清楚的问题，希望未来Demo和文档能更完善，这样子也方便更多人加入进来使用Hippy进行开发。目前网上能搜索到的使用Hippy开发的开源项目几乎没有，所以很多无脑疑问也只能在这里提出，不能去其他人的项目代码中寻找答案，目前正尝试看源码和学习前端开发知识寻找答案。

**Comment by CarryHekangkai** [comment]
HippyEngineContext.getInstance(instanceid)得到的HippyRootView为null，instanceid和HippyRootView的对应关系在哪里注册的？哪里能看到？

**Comment by CarryHekangkai** [comment]
代码注释中使用了大量的jsbundle，但jsbundle到底是什么？它跟index.android.js和vendor.android.js又有什么关系？

**Comment by CarryHekangkai** [comment]
> HippyEngineContext.getInstance(instanceid)得到的HippyRootView为null，instanceid和HippyRootView的对应关系在哪里注册的？哪里能看到？

目前发现instanceid指的是当前view所在根view的id

**Comment by zoomchan-cxj** [comment]
[webpack的分包原理](https://www.webpackjs.com/plugins/dll-plugin/)可以自行先了解一下，动态热更新由于苹果审核等原因，在开源版本是不提供的，需要业务自行实现，也可以加入我们的qq群784894901

**Comment by CarryHekangkai** [comment]
> hippy-react-demo编译出index.android.js和vendor.android.js，把index.android.js和vendor.android.js复制到android-demo中后，hippy-react-demo是否已经对项目正常运行没有作用了？仅index.android.js和vendor.android.js就可以支持项目正常运行？

目前测试仅需index.android.js和vendor.android.js就可以支持项目正常运行

**Comment by CarryHekangkai** [comment]
> index.android.js和vendor.android.js有什么作用？存在怎样的对应关系？index.android.js和vendor.android.js是必须以资源文件的形式打包在app内部而不能动态load吗？动态load index.android.js和vendor.android.js然后加载，这种方案是否可行？

可以从网络上load后保存在sd卡，通过设置coreJSFilePath和jsFilePath动态加载

**Comment by CarryHekangkai** [comment]
测试Demo：https://gitee.com/kangkai_hkk/hippy-demo.git

**Comment by churchill-zhang** [comment]
> ![image](https://user-images.githubusercontent.com/35455762/112798971-4fa03a80-90a0-11eb-8e35-8dfd6d5319d7.png)
> ![image](https://user-images.githubusercontent.com/35455762/112799037-647cce00-90a0-11eb-821b-5ef8969e17f6.png)
> 实在是搞不明白怎么在正式模式下进行设置远程服务器IP，只看到一个debugServerHost是DEBUG模式下用到的

正式不需要远程服务器IP，这里是debug用到的。一般调试是localhost调试，也可以设置debugServer ip进行远程调试
