### ISSUE TITLE
项目的 js 依赖配合是不是有问题

### ISSUE THREAD

**Issue by hsiaosiyuan0** [Tencent/Hippy#66]
> ### Start the iOS simulator with hippy-react or hippy-vue demo
>
> For iOS we recommend to use iOS simulator when first try, however, you may change the Xcode configuration to install the app to iPhone if you are a iOS expert.
>
> 1. Install the dependencies with `npm install`.
> 2. Build the front-end sdk packages with `npm run build`.
> 3. Choose a demo to build with `npm run buildexample -- [hippy-react-demo|hippy-vue-demo]`.
> 4. Start the Xcode and build the iOS app with `open examples/ios-demo/HippyDemo.xcodeproj`.

我看项目是用 lerna 来管理项目依赖的，对于上面的步骤，我尝试不使用 `npm install` 而是使用 `npx lerna bootstrap` 来替代，在接下来的 `npm run build` 时会报依赖错误：

```
> hippy@ build /ws/work/Hippy
> node ./scripts/js2cpp/build.js && node ./scripts/build.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@babel/core'
```

**Comment by xuqingkuang** [comment]
你没安装 SDK 依赖吧？js2cpp 是用来编译 [core/js](https://github.com/Tencent/Hippy/tree/master/core/js) 里的代码的。

**Comment by hsiaosiyuan0** [comment]
我的意思是，项目既然使用了 lerna 为什么不用 `lerna bootstrap` 来安装依赖，而是用 `npm install`

能接一个自动关闭 issue 的机器人么...

**Comment by hsiaosiyuan0** [comment]
目前直接 `npm install` 项目是可以跑起来，但是浏览 `packages/*` 下面的代码 Lint 工具还是会告警，除非手动运行 `lerna bootstrap` 链接一下，而实际上项目如果配置没问题的话，直接使用 `lerna bootstrap` 就会自动安装依赖并且在子项目间建立链接了
