### ISSUE TITLE
期望增加颜色渐变动画

### ISSUE THREAD

**Issue by mandycui** [Tencent/Hippy#663]
目前实现一个颜色渐变动画，css就是一句话，hippy需要实验两个view交替opacity，对业务很不友好，期望增加颜色渐变动画

**Comment by mandycui** [comment]
https://user-images.githubusercontent.com/10494907/112927504-add42880-9147-11eb-808f-13955d9fe53e.MP4
类似于视频内的搜索框的动画效果

**Comment by zoomchan-cxj** [comment]
#690 accomplished it
