### ISSUE TITLE
在运行  hippy:vendor 的时候报 WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.

### ISSUE THREAD

**Issue by hlbj105** [Tencent/Hippy#67]
![image](https://user-images.githubusercontent.com/16408650/71576376-71bcad00-2b2b-11ea-9013-493792c41fee.png)

执行npm run buildexample hippy-vue-demo 的时候，
![image](https://user-images.githubusercontent.com/16408650/71576400-8bf68b00-2b2b-11ea-988f-fb9f16866750.png)

**Comment by xuqingkuang** [comment]
webpack 的提示，因为在浏览器上超过 244kb 就算比较大的需要分包了，不过 Hippy 上没事不用管它。

第二个问题 README.md 里已经写了，暂时建议先使用 [ConEmu](https://conemu.github.io/) 来进行变变包操作。不过 #53 改完了就没那么麻烦了。
