### ISSUE TITLE
Layout 中的 flexShrink 默认值是否考虑和 w3c、Yoga 保持一致初始值为 1 呢？

### ISSUE THREAD

**Issue by meloalright** [Tencent/Hippy#672]
Hippy 的 sdk layout 中采用的 flexShrink 默认初始值为 0 [https://github.com/Tencent/Hippy/blob/87e2b66a8f28cc69bbde91f9e8834ebd2c2f17e8/ios/sdk/layout/MTTTStyle.cpp#L69](https://github.com/Tencent/Hippy/blob/87e2b66a8f28cc69bbde91f9e8834ebd2c2f17e8/ios/sdk/layout/MTTTStyle.cpp#L69)

而 w3c、Yoga 中都是默认初始值为 1
这里是否考虑未来和 w3c、Yoga 保持一致呢？

目前在有些场景引起了一些异常例如 #315

**Comment by zoomchan-cxj** [comment]
Duplicate of # #315
