### ISSUE TITLE
hippy-vue-demo的input组件报错

### ISSUE THREAD

**Issue by muzi86754781** [Tencent/Hippy#70]
点击清空文本内容的时候
this.$refs.inputDemo.childNodes.filter is not a function

**Comment by airyland** [comment]
DOM 标准中节点只是类数组，并没有 Array 的 find/filter 等各种方法，所以这里应该是代码写错了。
![image](https://user-images.githubusercontent.com/559179/71590692-73569700-2b64-11ea-9dcb-41796c9c380c.png)

**Comment by xuqingkuang** [comment]
嗯，这里可能得调整一下，没考虑到 Web 端兼容性。
