### ISSUE TITLE
 npm run build error

### ISSUE THREAD

**Issue by carl1990** [Tencent/Hippy#72]
mac OS ,excute   npm run build in iterm2, get error with info :

```
hippy@ build /Users/Carl/workspace/private/Hippy
> node ./scripts/js2cpp/build.js && node ./scripts/build.js

/Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js:54
let wraperFront_buffer = fs.readFileSync(`${__dirname}/wraperFront.js`);
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3

npm ERR! Darwin 18.7.0
npm ERR! argv "/Users/Carl/.nvm/versions/node/v4.1.2/bin/node" "/Users/Carl/.nvm/versions/node/v4.1.2/bin/npm" "run" "build"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! hippy@ build: `node ./scripts/js2cpp/build.js && node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hippy@ build script 'node ./scripts/js2cpp/build.js && node ./scripts/build.js'.
npm ERR! This is most likely a problem with the hippy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/js2cpp/build.js && node ./scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls hippy
```

**Comment by jeromehan** [comment]
> mac OS ,excute npm run build in iterm2, get error with info :
> 
> ```
> hippy@ build /Users/Carl/workspace/private/Hippy
> > node ./scripts/js2cpp/build.js && node ./scripts/build.js
> 
> /Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js:54
> let wraperFront_buffer = fs.readFileSync(`${__dirname}/wraperFront.js`);
> ^^^
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:413:25)
>     at Object.Module._extensions..js (module.js:452:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:475:10)
>     at startup (node.js:118:18)
>     at node.js:952:3
> 
> npm ERR! Darwin 18.7.0
> npm ERR! argv "/Users/Carl/.nvm/versions/node/v4.1.2/bin/node" "/Users/Carl/.nvm/versions/node/v4.1.2/bin/npm" "run" "build"
> npm ERR! node v4.1.2
> npm ERR! npm  v2.14.4
> npm ERR! code ELIFECYCLE
> npm ERR! hippy@ build: `node ./scripts/js2cpp/build.js && node ./scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the hippy@ build script 'node ./scripts/js2cpp/build.js && node ./scripts/build.js'.
> npm ERR! This is most likely a problem with the hippy package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./scripts/js2cpp/build.js && node ./scripts/build.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls hippy
> ```

"engines": {
    "node": ">=10.0.0"
  },
yarn安装推荐@1.9.4

**Comment by carl1990** [comment]
@jeromehan  
是node需要>= 10.0.0 
yarn需要1.9.4?

**Comment by jeromehan** [comment]
> @jeromehan
> 是node需要>= 10.0.0
> yarn需要1.9.4?

建议

**Comment by carl1990** [comment]
node v12.14.0
yarn 1.16.0

报错信息如下：

```
> hippy@ build /Users/Carl/workspace/private/Hippy
> node ./scripts/js2cpp/build.js && node ./scripts/build.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@babel/core'
Require stack:
- /Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hippy@ build: `node ./scripts/js2cpp/build.js && node ./scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hippy@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by xuqingkuang** [comment]
> node v12.14.0
> yarn 1.16.0
> 
> 报错信息如下：
> 
> ```
> > hippy@ build /Users/Carl/workspace/private/Hippy
> > node ./scripts/js2cpp/build.js && node ./scripts/build.js
> 
> internal/modules/cjs/loader.js:800
>     throw err;
>     ^
> 
> Error: Cannot find module '@babel/core'
> Require stack:
> - /Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js:4:15)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/Carl/workspace/private/Hippy/scripts/js2cpp/build.js' ]
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! hippy@ build: `node ./scripts/js2cpp/build.js && node ./scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the hippy@ build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> ```
```
npm ls @babel/core
```

如果没有的话 `rm -fr node_modules package-lock.json && npm install` 重装一下依赖。

**Comment by carl1990** [comment]
```
hippy@ build /Users/Carl/workspace/private/Hippy
> node ./scripts/js2cpp/build.js && node ./scripts/build.js

ios convert success, output /Users/Carl/workspace/private/Hippy/core/napi/jsc/native-source-code-ios.cc
android convert success, output /Users/Carl/workspace/private/Hippy/core/napi/v8/native-source-code-android.cc
Circular dependency: packages/hippy-react/src/dom/document-node.ts -> packages/hippy-react/src/dom/element-node.ts -> packages/hippy-react/src/dom/view-node.ts -> packages/hippy-react/src/dom/document-node.ts
packages/hippy-react/dist/index.js 114.02kb
packages/hippy-react-web/dist/index.js 62.97kb
'weex/runtime/recycle-list/render-component-template' is imported by node_modules/vue/src/core/vdom/create-component.js, but could not be resolved – treating it as an external dependency
Circular dependency: node_modules/vue/src/core/util/index.js -> node_modules/vue/src/core/util/options.js -> node_modules/vue/src/core/observer/index.js -> node_modules/vue/src/core/observer/dep.js -> node_modules/vue/src/core/util/index.js
Circular dependency: node_modules/vue/src/core/util/index.js -> node_modules/vue/src/core/util/options.js -> node_modules/vue/src/core/observer/index.js -> node_modules/vue/src/core/observer/array.js -> node_modules/vue/src/core/util/index.js
Circular dependency: node_modules/vue/src/core/util/index.js -> node_modules/vue/src/core/util/options.js -> node_modules/vue/src/core/observer/index.js -> node_modules/vue/src/core/util/index.js
Circular dependency: node_modules/vue/src/core/observer/watcher.js -> node_modules/vue/src/core/observer/scheduler.js -> node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/observer/watcher.js
Circular dependency: node_modules/vue/src/core/instance/init.js -> node_modules/vue/src/core/instance/state.js -> node_modules/vue/src/core/observer/watcher.js -> node_modules/vue/src/core/observer/scheduler.js -> node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/instance/init.js
Circular dependency: node_modules/vue/src/core/observer/scheduler.js -> node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/observer/scheduler.js
Circular dependency: node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/vdom/create-functional-component.js -> node_modules/vue/src/core/vdom/create-element.js
Circular dependency: node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/vdom/helpers/index.js
Circular dependency: node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/instance/lifecycle.js
Circular dependency: node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/helpers/index.js
Circular dependency: node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/instance/lifecycle.js
packages/hippy-vue/dist/index.js 383.89kb
'loader-utils' is imported by packages/hippy-vue-css-loader/src/index.js, but could not be resolved – treating it as an external dependency
packages/hippy-vue-css-loader/dist/index.js 25.33kb
packages/hippy-vue-native-components/dist/index.js 11.28kb
packages/hippy-vue-router/dist/index.js 56.41kb
```
这是成功了么？并没有报错信息，也没有app demo上面说的出现二维码呀

**Comment by jeromehan** [comment]
> ```
> hippy@ build /Users/Carl/workspace/private/Hippy
> > node ./scripts/js2cpp/build.js && node ./scripts/build.js
> 
> ios convert success, output /Users/Carl/workspace/private/Hippy/core/napi/jsc/native-source-code-ios.cc
> android convert success, output /Users/Carl/workspace/private/Hippy/core/napi/v8/native-source-code-android.cc
> Circular dependency: packages/hippy-react/src/dom/document-node.ts -> packages/hippy-react/src/dom/element-node.ts -> packages/hippy-react/src/dom/view-node.ts -> packages/hippy-react/src/dom/document-node.ts
> packages/hippy-react/dist/index.js 114.02kb
> packages/hippy-react-web/dist/index.js 62.97kb
> 'weex/runtime/recycle-list/render-component-template' is imported by node_modules/vue/src/core/vdom/create-component.js, but could not be resolved – treating it as an external dependency
> Circular dependency: node_modules/vue/src/core/util/index.js -> node_modules/vue/src/core/util/options.js -> node_modules/vue/src/core/observer/index.js -> node_modules/vue/src/core/observer/dep.js -> node_modules/vue/src/core/util/index.js
> Circular dependency: node_modules/vue/src/core/util/index.js -> node_modules/vue/src/core/util/options.js -> node_modules/vue/src/core/observer/index.js -> node_modules/vue/src/core/observer/array.js -> node_modules/vue/src/core/util/index.js
> Circular dependency: node_modules/vue/src/core/util/index.js -> node_modules/vue/src/core/util/options.js -> node_modules/vue/src/core/observer/index.js -> node_modules/vue/src/core/util/index.js
> Circular dependency: node_modules/vue/src/core/observer/watcher.js -> node_modules/vue/src/core/observer/scheduler.js -> node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/observer/watcher.js
> Circular dependency: node_modules/vue/src/core/instance/init.js -> node_modules/vue/src/core/instance/state.js -> node_modules/vue/src/core/observer/watcher.js -> node_modules/vue/src/core/observer/scheduler.js -> node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/instance/init.js
> Circular dependency: node_modules/vue/src/core/observer/scheduler.js -> node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/observer/scheduler.js
> Circular dependency: node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/vdom/create-functional-component.js -> node_modules/vue/src/core/vdom/create-element.js
> Circular dependency: node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/vdom/helpers/index.js
> Circular dependency: node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/create-component.js -> node_modules/vue/src/core/instance/lifecycle.js
> Circular dependency: node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/vdom/create-element.js -> node_modules/vue/src/core/vdom/helpers/index.js
> Circular dependency: node_modules/vue/src/core/instance/lifecycle.js -> node_modules/vue/src/core/instance/events.js -> node_modules/vue/src/core/vdom/helpers/index.js -> node_modules/vue/src/core/vdom/helpers/resolve-async-component.js -> node_modules/vue/src/core/instance/render.js -> node_modules/vue/src/core/instance/lifecycle.js
> packages/hippy-vue/dist/index.js 383.89kb
> 'loader-utils' is imported by packages/hippy-vue-css-loader/src/index.js, but could not be resolved – treating it as an external dependency
> packages/hippy-vue-css-loader/dist/index.js 25.33kb
> packages/hippy-vue-native-components/dist/index.js 11.28kb
> packages/hippy-vue-router/dist/index.js 56.41kb
> ```
> 
> 这是成功了么？并没有报错信息，也没有app demo上面说的出现二维码呀

![image](https://user-images.githubusercontent.com/19773879/72810444-860e4880-3c98-11ea-86a1-6e9d418b7893.png)
npm run build 只是编译前端sdk. 看readme.md

**Comment by xuqingkuang** [comment]
It seems no update, close it first.
