### ISSUE TITLE
没有脚手架怎么开发项目？

### ISSUE THREAD

**Issue by Carson-czl** [Tencent/Hippy#720]
提供的cra-template-hippy-react脚手架根本运行不了，安卓目录结构也没有ios也是一样
vue开发者如何开发？demo目录里没有安卓结构和ios结构没法运行

**Comment by zoomchan-cxj** [comment]
可以直接基于 example的 js demo来开发，demo的scripts里包含了需要使用的全部前端编译脚本，可以先试下按照readme的步骤初始化一个项目
