### ISSUE TITLE
Android 编译报错

### ISSUE THREAD

**Issue by zy654781296** [Tencent/Hippy#73]
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.

**Comment by zy654781296** [comment]
@jeromehan

**Comment by jeromehan** [comment]
> @jeromehan

Ninja确认安装之后、配置Ninja环境变量

**Comment by zy654781296** [comment]
![png](https://raw.githubusercontent.com/zy654781296/Notes/master/images/1.png)
![png](https://raw.githubusercontent.com/zy654781296/Notes/master/images/2.png)

@jeromehan

**Comment by jeromehan** [comment]
> ![png](https://raw.githubusercontent.com/zy654781296/Notes/master/images/1.png)
> ![png](https://raw.githubusercontent.com/zy654781296/Notes/master/images/2.png)
> 
> @jeromehan
brew install ninja

**Comment by jeromehan** [comment]
> > ![png](https://raw.githubusercontent.com/zy654781296/Notes/master/images/1.png)
> > ![png](https://raw.githubusercontent.com/zy654781296/Notes/master/images/2.png)
> > @jeromehan
> > brew install ninja

mac 有的机型比较诡异，brew install ninja就好了

**Comment by zy654781296** [comment]
我去，还真的是啊，brew install 就好了，真是奇葩呀。
