### ISSUE TITLE
【android，mac】执行hippy:debug命令正常，但是设备无法连接上

### ISSUE THREAD

**Issue by jamesxieliang11** [Tencent/Hippy#746]
**Describe the bug**
【android，mac】执行hippy:debug命令正常，但是设备无法连接上，报错Error: chrome msg received, but androidClient not attached
**To Reproduce**

1. 运行adb 38989端口
2.usb链接安卓打开调试模式 执行 adb devices 
![image](https://user-images.githubusercontent.com/20868448/117539036-34c7cb00-b03b-11eb-9c68-71eb0f6fc144.png)

3. 执行命令hippy:debug
4. 打开debug工具
![image](https://user-images.githubusercontent.com/20868448/117539059-62ad0f80-b03b-11eb-964f-55da5fbc49af.png)
5. 控制台报错
 Error: chrome msg received, but androidClient not attached

**Expected behavior**
期望安卓能够真机调试
**Screenshots**

**Smartphone (please complete the following information):**

- Device: 小米10至尊版 qq浏览器
- OS and version: miui 12.0.15
- Hippy native SDK version: hippy-cli: "^2.2.1"
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

**Comment by zoomchan-cxj** [comment]
1. debug前先执行 adb reverse --remove-all &&  adb reverse tcp:38989 tcp:3898
2. 建议将终端sdk 升级到最新
