### ISSUE TITLE
min-heigth 不支持 100vh ?

### ISSUE THREAD

**Issue by ElfSundae** [Tencent/Hippy#75]
- hippy-vue-demo
- iOS 13.3

Vue Example 中点击 `iframe 组件`，弹出错误如下：

![image](https://user-images.githubusercontent.com/526008/71617230-1d7dff80-2bf5-11ea-9be3-ff60d5185c95.png)
Xcode 日志一直在输出：
```
HippyDemo[16854:3598818] [Process] kill() returned unexpected error 1
```

**Comment by jeromehan** [comment]
> * hippy-vue-demo
> * iOS 13.3
> 
> Vue Example 中点击 `iframe 组件`，弹出错误如下：
> 
> ![image](https://user-images.githubusercontent.com/526008/71617230-1d7dff80-2bf5-11ea-9be3-ff60d5185c95.png)
> Xcode 日志一直在输出：
> 
> ```
> HippyDemo[16854:3598818] [Process] kill() returned unexpected error 1
> ```

![image](https://user-images.githubusercontent.com/19773879/71617463-2c18e680-2bf6-11ea-8698-db6c10127966.png)

**Comment by xuqingkuang** [comment]
确实不支持相对单位，这个在官网里有说。

这个问题是临开源前发现 iframe 在浏览器里无法撑满剩余空间写的。
