### ISSUE TITLE
ListView什么时候可以支持横向

### ISSUE THREAD

**Issue by iyang519** [Tencent/Hippy#795]
1.目前ScrollView支持横向滑动，但ScrollView会渲染全部节点，导致内存上涨；

2.希望ListView可以支持横向滑动，只渲染上屏节点；
目前安卓支持设置horizontal属性，但renderRow里节点设置width不生效，只能是屏幕的宽度；
ios不支持横向；

**Comment by zoomchan-cxj** [comment]
安卓可以通过ListView的getRowStyle设置item宽度
