### ISSUE TITLE
有详细一点的文档嘛

### ISSUE THREAD

**Issue by zhaoli703098596** [Tencent/Hippy#80]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xuqingkuang** [comment]
我觉得已经够详细了，觉得哪儿还不够详细可以发 issue 把缺少的部分描述清楚，我可以补上。

现在这样泛而笼统的问题描述其实没有任何帮助。
