### ISSUE TITLE
会推出hippy生态相关产品吗，类似QMUI hippy版

### ISSUE THREAD

**Issue by fubd** [Tencent/Hippy#81]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xuqingkuang** [comment]
官方不会出，没有那么大精力同时维护那么多项目，目前社区内同类框架也都是由社区提供支持，在腾讯内部 Hippy 的组件库也是由其它业务项目组研发的。
