### ISSUE TITLE
ListView初始位移值（initialContentOffset）属性设置不生效

### ISSUE THREAD

**Issue by zjf1165** [Tencent/Hippy#827]
<img width="1462" alt="wecom-temp-75ee1d6cd8ff151a70e52c3d709e2f36" src="https://user-images.githubusercontent.com/13042884/123217328-09227680-d4fd-11eb-8be0-6d315864294f.png">
initialContentOffset属性设置不生效，源码中未看到，请求官方支持

**Comment by zoomchan-cxj** [comment]
目前只有ios支持，文档已经修改，后面android会补上
