### ISSUE TITLE
[hippy-react] Native.addEventListener 接口未直接暴露

### ISSUE THREAD

**Issue by XyyF** [Tencent/Hippy#829]
**Is your feature request related to a problem? Please describe.**
1. 通过监听Hippy实例销毁事件 `destroyInstance` 处理相关逻辑，但是 `addEventListener`  接口并没有直接暴露，而是通过`Hippy.Native`的静态属性获取Native，再进行监听；这样使用存在接口变更风险，也有相关warn提示不应如此使用；

Hippy.Native.addEventListener('destroyInstance', () => {});

2. 尝试使用 `hippyEventEmitter` 去监听 `destroyInstance` 事件没有触发；
3. 文档中说明通过 `Hippy.on` 去监听，但是并无该方法；

**Describe the solution you'd like**
addEventListener 接口并未直接暴露，是有什么原因考量吗？希望能将该接口export出来

**Comment by zoomchan-cxj** [comment]
1. `Hippy.on` 是挂载在全局变量global下面 [Hippy.on 的声明](https://github.com/Tencent/Hippy/blob/master/core/js/global/Others.js#L105)
2. [addEventListener导出](https://github.com/Tencent/Hippy/blob/master/packages/hippy-react/src/global.ts#L30)，可以看到其实`addEventListener` 与 `Hippy.on` 是等价的

**Comment by XyyF** [comment]
明白了，感谢
