### ISSUE TITLE
npm run hippy:dev 报错 Module not found: Error: Can't resolve 'vue' 

### ISSUE THREAD

**Issue by zbser** [Tencent/Hippy#84]
下载了这里的DEMO
https://git.code.tencent.com/Tencent_Open_Source/Hippy

安装这里的说明文档操作
https://tencent.github.io/Hippy/#/guide/debug

在终端进入了 /Users/Zbs/Desktop/Hippy/hippy-main/examples/hippy-vue-demo 目录
执行了安装依赖 `npm i`，提示是成功的
![截屏2020-01-0322 39 11](https://user-images.githubusercontent.com/20149809/71729153-f71cc600-2e79-11ea-9775-d1249c31b2e7.png)

但是在执行 `npm run hippy:dev` 却不能报了如下错误：
Module not found: Error: Can't resolve 'vue' in '/Users/Zbs/Desktop/Hippy/hippy-main/examples/hippy-vue-demo/src/components/list-items'
Module not found: Error: Can't resolve 'vue-router' in '/Users/Zbs/Desktop/Hippy/hippy-main/examples/hippy-vue-demo/src'

![截屏2020-01-0322 42 34](https://user-images.githubusercontent.com/20149809/71729407-9641bd80-2e7a-11ea-9ac6-ee806b31d032.png)

![截屏2020-01-0322 42 47](https://user-images.githubusercontent.com/20149809/71729417-9c379e80-2e7a-11ea-9f89-06f3140911d1.png)

![截屏2020-01-0322 42 55](https://user-images.githubusercontent.com/20149809/71729424-a3f74300-2e7a-11ea-9180-57d30bacb0d5.png)

我看相关的vue 和 vue-router 都是在的，很奇怪，不知道哪里出错了？求指导，谢谢。

![截屏2020-01-0322 45 53](https://user-images.githubusercontent.com/20149809/71729567-0ea87e80-2e7b-11ea-83e5-2960bc7bc40e.png)

![截屏2020-01-0322 46 22](https://user-images.githubusercontent.com/20149809/71729582-15cf8c80-2e7b-11ea-8077-5900f24a0ddb.png)

**Comment by xuqingkuang** [comment]
duplicated with #79 

文档是文档，是给你启动自己的项目开发的，运行 hippy 项目还请仔细看 hippy 的 README。

**Comment by zbser** [comment]
> duplicated with #79
> 
> 文档是文档，是给你启动自己的项目开发的，运行 hippy 项目还请仔细看 hippy 的 README。

https://github.com/Tencent/Hippy/blob/master/README.zh_CN.md
根据这里说明，正常解决，忽略了，谢谢指导
