### ISSUE TITLE
CMake Issuse with Ninja 

### ISSUE THREAD

**Issue by cmpeguerog** [Tencent/Hippy#85]
**Gradle Build output**
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

IDE: Android Studio 3.5.3.
OS: Windows 64 Bits.
NDK: 20.1.5948944.

**Note :**
Android SDK cmake already added to system path.

**Comment by xuqingkuang** [comment]
Duplicated with #39
