### ISSUE TITLE
安卓端 listView 横屏pullHeader宽度撑满了一屏

### ISSUE THREAD

**Issue by GolLight** [Tencent/Hippy#862]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- OS and version: [e.g. iOS 13.3.1]
- Hippy native SDK version: [e.g. 2.0.0]
- Front-end SDK and version [e.g. @hippy/vue 2.0.1]

**Additional context**

**Comment by zoomchan-cxj** [comment]
可以通过ListView的getHeaderStyle方法显式设置宽度
