### ISSUE TITLE
[Hippy-Vue]ScrollView的onScrollEndDrag事件无终端参数

### ISSUE THREAD

**Issue by 7Finn** [Tencent/Hippy#866]
**Describe the bug**
Hippy-Vue中ScrollView的onScrollEndDrag事件无返回终端参数。
onScroll的回调参数event中会有event.offsetX和event.offsetY。
但onScrollEndDrag中没有。

PS: **Hippy-React中的onScrollEndDrag事件的回调参数会有contentOffset: { x, y }，两端的事件并没有对齐**

**To Reproduce**

1. 创建一个div，加上样式overflow-x: scroll;
2. 在div中添加事件@scrollEndDrag="handleScrollEndDrag"
3. 在handleScrollEndDrag的函数中输出参数event
```
handleScrollEndDrag(event) {
    console.log(event);
}
```
4. 可以看到event中没有任何与offset相关的属性。

**Expected behavior**
event应该要有当前offset的x, y。

**Screenshots**

**Smartphone (please complete the following information):**

- Front-end SDK and version:
"@hippy/vue": "^2.5.4",
"@hippy/vue-native-components": "^2.5.4",

**Comment by zoomchan-cxj** [comment]
下个版本我们修复一下
