### ISSUE TITLE
npm run hippy:debug 报错

### ISSUE THREAD

**Issue by leirenbaobao** [Tencent/Hippy#89]
npm run hippy:debug

> hippy-react-demo@2.0.0 hippy:debug ***/Hippy/examples/hippy-react-demo
> hippy-debug

ℹ  Hippy debug server is started, you can open "chrome://inspect" in Chrome to debug your Hippy app now.
⚠  Port reverse failed, please execute command manually if you need android debugging: adb reverse --remove-all && adb reverse tcp:38989 tcp:38989
✖  Error: spawn adb ENOENT 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by zousandian** [comment]
目前貌似只支持 android，先要 adb 连接设备成功才行

**Comment by xuqingkuang** [comment]
这个一般是没装 adb 导致的，如果只需要 iOS 调试的话可以忽略。

如果需要 Android 调试的话，请先安装好 Android Studio，并且确认已经把 `Android/sdk/platform-tools` 加到 PATH 里让命令行可以搜索到。

Mac 下可以这么干。

```bash
export PATH=$PATH:$HOME/Library/Android/sdk/platform-tools
```

然后重新运行 `npm run hippy:debug` 就行。

**Comment by perryhong** [comment]
![image](https://user-images.githubusercontent.com/39239212/82563249-47868d00-9ba9-11ea-96dd-8dbe36855fcf.png)
![image](https://user-images.githubusercontent.com/39239212/82563269-54a37c00-9ba9-11ea-817c-e5a298a30d01.png)
