### ISSUE TITLE
能不能考虑兼容到4.0以上设备，现在在4.2.2上面会有加载so库报错问题

### ISSUE THREAD

**Issue by caowenjun** [Tencent/Hippy#942]
运行example项目会有以下报错信息：
dlopen("/mnt/asec/com.tencent.mtt.hippy.example-1/lib/libhippybridge.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libv8.cr.so" needed by "libhippybridge.so"; caused by load_library(linker.cpp:745): library "libv8.cr.so" not found

**Comment by zoomchan-cxj** [comment]
4.0系统加载so android 有bug，需要手动load相关so，可以手动在Java加载所有依赖的so
