### ISSUE TITLE
修复Text在缩略的情况下，emoji被截断的问题。

### ISSUE THREAD

**Issue by zhazhaxia** [Tencent/Hippy#950]
描述：
在Android下，文本缩略的时候，如果末尾是emoji，会有编码缩略异常。
如图：
![image](https://user-images.githubusercontent.com/8816884/130921082-f540070f-3b17-4884-a034-857e597a88f9.png)

这里猜测是unicode截断了。

麻烦官方修复下，感谢。

**Comment by zoomchan-cxj** [comment]
[This PR](https://github.com/Tencent/Hippy/pull/2221) has fixed it
